
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-08T22:08:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4100072472417867721abd61344a8e64032c1dc",
 "version": "1.9.2.post.dev31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
