
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "branch": "0.12.0)",
 "date": "2020-05-18T14:47:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a15883bea96dff10754f18fccadbefd0647bb5b3",
 "repository": "https://github.com/metawards/MetaWards",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
