
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-12T09:24:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b046ad464dbbe996ebfa5d61ce9152dd612ee477",
 "version": "0.6.104"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
