
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-13T20:45:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c7862392896458ec031f92eea2c7a6f6f71608d",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
