
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-18T09:40:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "66fd02fff46b81cf0a4505fe8cad7288777e4b62",
 "version": "1.9.4.post.dev45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
