
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-15T12:22:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a54c051cc77d322956fe843eeddc3cddaf68b8cd",
 "version": "0.0.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
