
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-16T01:51:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecc1e6e339a5a7be958c328403517cd547873d7e",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
