# coding: utf-8

"""
    ARLAS CITY API

    ARLAS-city content manager

    OpenAPI spec version: 0.1.0
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import arlas_city_api_python
from arlas_city_api_python.rest import ApiException
from arlas_city_api_python.models.filter import Filter


class TestFilter(unittest.TestCase):
    """ Filter unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilter(self):
        """
        Test Filter
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = arlas_city_api_python.models.filter.Filter()
        pass


if __name__ == '__main__':
    unittest.main()
