
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-08T17:51:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f60a7d7e9195a1a095204c4b7de8a5136287ef7",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
