
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-18T16:05:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7ee7e9a98e393ced8c6a9c4ce2dc69198710170",
 "version": "0.0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
