
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-10T01:05:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd3190f418b0dc58128e030eab1e564ef4fd513d",
 "version": "v2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
