
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-14T18:22:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9320558f607e8c9a1ae9fddf8d95015570bbfc40",
 "version": "0.10.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
