# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matrix.proto',
  package='matrices',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'),
  serialized_pb=_b('\n\x0cmatrix.proto\x12\x08matrices\"\x18\n\x08Neighbor\x12\x0c\n\x04name\x18\x01 \x01(\t\"1\n\x0cNeighborList\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.matrices.Neighbor\"&\n\x06Matrix\x12\x0e\n\x06\x61pikey\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\"\n\x06\x45ntity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"P\n\x08\x45ntities\x12 \n\x06matrix\x18\x01 \x01(\x0b\x32\x10.matrices.Matrix\x12\"\n\x08\x65ntities\x18\x02 \x03(\x0b\x32\x10.matrices.Entity\"\x1c\n\x0c\x46\x65\x61tureStore\x12\x0c\n\x04name\x18\x01 \x01(\t\"T\n\tNNRequest\x12 \n\x06matrix\x18\x01 \x01(\x0b\x32\x10.matrices.Matrix\x12\x0e\n\x06\x65ntity\x18\x02 \x01(\t\x12\x15\n\rnum_neighbors\x18\x03 \x01(\x05\"/\n\nVectorDict\x12!\n\x07vectors\x18\x01 \x03(\x0b\x32\x10.matrices.Vector\"\'\n\nStringItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"2\n\x0b\x46\x65\x61tureList\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.matrices.StringItem\"1\n\nEntityList\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.matrices.StringItem\"\'\n\nVectorItem\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x02\"=\n\x06Vector\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\t\x12#\n\x05items\x18\x02 \x03(\x0b\x32\x14.matrices.VectorItem\"\"\n\x0eStringResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xfb\x02\n\rMatrixBackend\x12\x37\n\tGetVector\x12\x16.matrices.FeatureStore\x1a\x10.matrices.Vector\"\x00\x12\x44\n\x13GetNearestNeighbors\x12\x13.matrices.NNRequest\x1a\x16.matrices.NeighborList\"\x00\x12\x38\n\x0bGetFeatures\x12\x10.matrices.Matrix\x1a\x15.matrices.FeatureList\"\x00\x12\x37\n\x0bGetEntities\x12\x10.matrices.Matrix\x1a\x14.matrices.EntityList\"\x00\x12>\n\x10GetEntityVectors\x12\x12.matrices.Entities\x1a\x14.matrices.VectorDict\"\x00\x12\x38\n\x08SaveTree\x12\x10.matrices.Matrix\x1a\x18.matrices.StringResponse\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_NEIGHBOR = _descriptor.Descriptor(
  name='Neighbor',
  full_name='matrices.Neighbor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='matrices.Neighbor.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=50,
)


_NEIGHBORLIST = _descriptor.Descriptor(
  name='NeighborList',
  full_name='matrices.NeighborList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='matrices.NeighborList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=101,
)


_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='matrices.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apikey', full_name='matrices.Matrix.apikey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='matrices.Matrix.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=141,
)


_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='matrices.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='matrices.Entity.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='matrices.Entity.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=177,
)


_ENTITIES = _descriptor.Descriptor(
  name='Entities',
  full_name='matrices.Entities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix', full_name='matrices.Entities.matrix', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entities', full_name='matrices.Entities.entities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=259,
)


_FEATURESTORE = _descriptor.Descriptor(
  name='FeatureStore',
  full_name='matrices.FeatureStore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='matrices.FeatureStore.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=289,
)


_NNREQUEST = _descriptor.Descriptor(
  name='NNRequest',
  full_name='matrices.NNRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix', full_name='matrices.NNRequest.matrix', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity', full_name='matrices.NNRequest.entity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_neighbors', full_name='matrices.NNRequest.num_neighbors', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=375,
)


_VECTORDICT = _descriptor.Descriptor(
  name='VectorDict',
  full_name='matrices.VectorDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vectors', full_name='matrices.VectorDict.vectors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=424,
)


_STRINGITEM = _descriptor.Descriptor(
  name='StringItem',
  full_name='matrices.StringItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='matrices.StringItem.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='matrices.StringItem.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=465,
)


_FEATURELIST = _descriptor.Descriptor(
  name='FeatureList',
  full_name='matrices.FeatureList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='matrices.FeatureList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=517,
)


_ENTITYLIST = _descriptor.Descriptor(
  name='EntityList',
  full_name='matrices.EntityList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='matrices.EntityList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=568,
)


_VECTORITEM = _descriptor.Descriptor(
  name='VectorItem',
  full_name='matrices.VectorItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='matrices.VectorItem.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='matrices.VectorItem.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=609,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='matrices.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='matrices.Vector.entity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='matrices.Vector.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=672,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='matrices.StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='matrices.StringResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=708,
)

_NEIGHBORLIST.fields_by_name['items'].message_type = _NEIGHBOR
_ENTITIES.fields_by_name['matrix'].message_type = _MATRIX
_ENTITIES.fields_by_name['entities'].message_type = _ENTITY
_NNREQUEST.fields_by_name['matrix'].message_type = _MATRIX
_VECTORDICT.fields_by_name['vectors'].message_type = _VECTOR
_FEATURELIST.fields_by_name['items'].message_type = _STRINGITEM
_ENTITYLIST.fields_by_name['items'].message_type = _STRINGITEM
_VECTOR.fields_by_name['items'].message_type = _VECTORITEM
DESCRIPTOR.message_types_by_name['Neighbor'] = _NEIGHBOR
DESCRIPTOR.message_types_by_name['NeighborList'] = _NEIGHBORLIST
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
DESCRIPTOR.message_types_by_name['Entities'] = _ENTITIES
DESCRIPTOR.message_types_by_name['FeatureStore'] = _FEATURESTORE
DESCRIPTOR.message_types_by_name['NNRequest'] = _NNREQUEST
DESCRIPTOR.message_types_by_name['VectorDict'] = _VECTORDICT
DESCRIPTOR.message_types_by_name['StringItem'] = _STRINGITEM
DESCRIPTOR.message_types_by_name['FeatureList'] = _FEATURELIST
DESCRIPTOR.message_types_by_name['EntityList'] = _ENTITYLIST
DESCRIPTOR.message_types_by_name['VectorItem'] = _VECTORITEM
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Neighbor = _reflection.GeneratedProtocolMessageType('Neighbor', (_message.Message,), dict(
  DESCRIPTOR = _NEIGHBOR,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.Neighbor)
  ))
_sym_db.RegisterMessage(Neighbor)

NeighborList = _reflection.GeneratedProtocolMessageType('NeighborList', (_message.Message,), dict(
  DESCRIPTOR = _NEIGHBORLIST,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.NeighborList)
  ))
_sym_db.RegisterMessage(NeighborList)

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), dict(
  DESCRIPTOR = _MATRIX,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.Matrix)
  ))
_sym_db.RegisterMessage(Matrix)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), dict(
  DESCRIPTOR = _ENTITY,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.Entity)
  ))
_sym_db.RegisterMessage(Entity)

Entities = _reflection.GeneratedProtocolMessageType('Entities', (_message.Message,), dict(
  DESCRIPTOR = _ENTITIES,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.Entities)
  ))
_sym_db.RegisterMessage(Entities)

FeatureStore = _reflection.GeneratedProtocolMessageType('FeatureStore', (_message.Message,), dict(
  DESCRIPTOR = _FEATURESTORE,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.FeatureStore)
  ))
_sym_db.RegisterMessage(FeatureStore)

NNRequest = _reflection.GeneratedProtocolMessageType('NNRequest', (_message.Message,), dict(
  DESCRIPTOR = _NNREQUEST,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.NNRequest)
  ))
_sym_db.RegisterMessage(NNRequest)

VectorDict = _reflection.GeneratedProtocolMessageType('VectorDict', (_message.Message,), dict(
  DESCRIPTOR = _VECTORDICT,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.VectorDict)
  ))
_sym_db.RegisterMessage(VectorDict)

StringItem = _reflection.GeneratedProtocolMessageType('StringItem', (_message.Message,), dict(
  DESCRIPTOR = _STRINGITEM,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.StringItem)
  ))
_sym_db.RegisterMessage(StringItem)

FeatureList = _reflection.GeneratedProtocolMessageType('FeatureList', (_message.Message,), dict(
  DESCRIPTOR = _FEATURELIST,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.FeatureList)
  ))
_sym_db.RegisterMessage(FeatureList)

EntityList = _reflection.GeneratedProtocolMessageType('EntityList', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYLIST,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.EntityList)
  ))
_sym_db.RegisterMessage(EntityList)

VectorItem = _reflection.GeneratedProtocolMessageType('VectorItem', (_message.Message,), dict(
  DESCRIPTOR = _VECTORITEM,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.VectorItem)
  ))
_sym_db.RegisterMessage(VectorItem)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.Vector)
  ))
_sym_db.RegisterMessage(Vector)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGRESPONSE,
  __module__ = 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrices.StringResponse)
  ))
_sym_db.RegisterMessage(StringResponse)


DESCRIPTOR._options = None

_MATRIXBACKEND = _descriptor.ServiceDescriptor(
  name='MatrixBackend',
  full_name='matrices.MatrixBackend',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=711,
  serialized_end=1090,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVector',
    full_name='matrices.MatrixBackend.GetVector',
    index=0,
    containing_service=None,
    input_type=_FEATURESTORE,
    output_type=_VECTOR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNearestNeighbors',
    full_name='matrices.MatrixBackend.GetNearestNeighbors',
    index=1,
    containing_service=None,
    input_type=_NNREQUEST,
    output_type=_NEIGHBORLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFeatures',
    full_name='matrices.MatrixBackend.GetFeatures',
    index=2,
    containing_service=None,
    input_type=_MATRIX,
    output_type=_FEATURELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEntities',
    full_name='matrices.MatrixBackend.GetEntities',
    index=3,
    containing_service=None,
    input_type=_MATRIX,
    output_type=_ENTITYLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEntityVectors',
    full_name='matrices.MatrixBackend.GetEntityVectors',
    index=4,
    containing_service=None,
    input_type=_ENTITIES,
    output_type=_VECTORDICT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaveTree',
    full_name='matrices.MatrixBackend.SaveTree',
    index=5,
    containing_service=None,
    input_type=_MATRIX,
    output_type=_STRINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATRIXBACKEND)

DESCRIPTOR.services_by_name['MatrixBackend'] = _MATRIXBACKEND

# @@protoc_insertion_point(module_scope)
