
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-13T20:52:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f61cfb8acfa2e4f905fea5dae367d54285770d34",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
