
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-05-08T18:19:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ac2f33c02b29dda2598ed811d5305c552ad9ee2",
 "version": "0.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
