
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-09T17:11:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1106169f98b070dfe887e30d59251661cce5a464",
 "version": "0.11.0b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
