
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4150fcf630ae3dd1320dc6e21d46d8de25da0bdf",
 "version": "0.0.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
