
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-12T13:44:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "657974cabfa3eab7acc634f41148fc2a0eb13e59",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
