# coding: utf-8

"""
    ARLAS CITY API

    ARLAS-city content manager

    OpenAPI spec version: 0.1.0
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ValidationReport(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agencies': 'list[str]',
        'statistics': 'FeedStatistics',
        'validation': 'ValidationResults'
    }

    attribute_map = {
        'agencies': 'agencies',
        'statistics': 'statistics',
        'validation': 'validation'
    }

    def __init__(self, agencies=None, statistics=None, validation=None):
        """
        ValidationReport - a model defined in Swagger
        """

        self._agencies = None
        self._statistics = None
        self._validation = None

        if agencies is not None:
          self.agencies = agencies
        if statistics is not None:
          self.statistics = statistics
        if validation is not None:
          self.validation = validation

    @property
    def agencies(self):
        """
        Gets the agencies of this ValidationReport.

        :return: The agencies of this ValidationReport.
        :rtype: list[str]
        """
        return self._agencies

    @agencies.setter
    def agencies(self, agencies):
        """
        Sets the agencies of this ValidationReport.

        :param agencies: The agencies of this ValidationReport.
        :type: list[str]
        """

        self._agencies = agencies

    @property
    def statistics(self):
        """
        Gets the statistics of this ValidationReport.

        :return: The statistics of this ValidationReport.
        :rtype: FeedStatistics
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics):
        """
        Sets the statistics of this ValidationReport.

        :param statistics: The statistics of this ValidationReport.
        :type: FeedStatistics
        """

        self._statistics = statistics

    @property
    def validation(self):
        """
        Gets the validation of this ValidationReport.

        :return: The validation of this ValidationReport.
        :rtype: ValidationResults
        """
        return self._validation

    @validation.setter
    def validation(self, validation):
        """
        Sets the validation of this ValidationReport.

        :param validation: The validation of this ValidationReport.
        :type: ValidationResults
        """

        self._validation = validation

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ValidationReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
