
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-15T15:35:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "854f49759a1eeb6c51ddeaa03668902a21523325",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
