# AUTOGENERATED! DO NOT EDIT! File to edit: 01_schema.ipynb (unless otherwise specified).

__all__ = ['get_schema']

# Cell
from dotenv import load_dotenv
load_dotenv()
from google.cloud import bigquery


def get_schema(table_id):
    """Get schema given a table_id.
    """
    client = bigquery.Client()
    table = client.get_table(table_id)
    schema = table.schema
    return schema