
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-19T09:28:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cb0173109442dbd04a05898ff040eb9ea041360",
 "version": "1.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
