
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-16T12:15:09+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "647e4f834dcf0b91ca1c910bf9e51576e0c28bfa",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
