
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-12T10:50:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "22eceb25d2f6aa0d902b370397a82cb9cc1b8a5d",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
