class COMMON_KEYS:
    ESC = "53"
    DELETE = "51"
    TAB = "48"
    LSHIFT = "57"
    RSHIFT = "60"
    FN = "63"
    CONTROL = "59"
    OPTION = "58"
    COMMAND = "55"
    SPACE = "49"
    RETURN = "36"
    ENTER = "76"
    ARROW_UP =  "126"
    ARROW_DOWN = "125"
    ARROW_LEFT = "123"
    ARROW_RIGHT = "124"
    HOME = "115"
    END = "119"
    PAGE_UP = "116"
    PAGE_DOWN = "121"


class ALPHABETS:
    q = "12"
    w = "13"
    e = "14"
    r = "15"
    t = "17"
    y = "16"
    u = "32"
    i = "34"
    o = "31"
    p = "35"
    a = "0"
    s = "1"
    d = "2"
    f = "3"
    g = "5"
    h = "4"
    j = "38"
    k = "40"
    l = "37"
    z = "6"
    x = "7"
    c = "8"
    v = "9"
    b = "11"
    n = "45"
    m = "46"
    Q = "12 using shift down"
    W = "13 using shift down"
    E = "14 using shift down"
    R = "15 using shift down"
    T = "17 using shift down"
    Y = "16 using shift down"
    U = "32 using shift down"
    I = "34 using shift down"
    O = "31 using shift down"
    P = "35 using shift down"
    A = "0 using shift down"
    S = "1 using shift down"
    D = "2 using shift down"
    F = "3 using shift down"
    G = "5 using shift down"
    H = "4 using shift down"
    J = "38 using shift down"
    K = "40 using shift down"
    L = "37 using shift down"
    Z = "6 using shift down"
    X = "7 using shift down"
    C = "8 using shift down"
    V = "9 using shift down"
    B = "11 using shift down"
    N = "45 using shift down"
    M = "46 using shift down"


class NUMBERS:
    ONE = "18"
    TWO = "19"
    THREE = "20"
    FOUR = "21"
    FIVE = "23"
    SIX = "22"
    SEVEN = "26"
    EIGHT = "28"
    NINE = "25"
    ZERO = "29"


class FUNCT_KEYS:
    F1 = "122"
    F2 = "120"
    F3 = "99"
    F4 = "118"
    F5 = "96"
    F6 = "97"
    F7 = "98"
    F8 = "100"
    F9 = "101"
    F10 = "109"
    F11 = "103"
    F12 = "111"


class SPECIAL_CHARS:
    TILDE = "50 using shift down"
    BRACKET_OPEN = "33"
    CURLYBRACKET_OPEN = "33 using shift down"
    BRACKET_CLOSE = "30"
    CURLYBRACKET_CLOSE = "30 using shift down"
    BACKSLASH = "42"
    PIPE = "42 using shift down"
    SEMICOLON = "41"
    COLON = "41 using shift down"
    SINGLEQUOTE = "39"
    DOUBLEQUOTE = " 39 using shift down"
    COMA = "43"
    LESSTHAN = "43 using shift down"
    PERIOD = "47"
    GREATERTHAN = "47 using shift down"
    FORWARDSLASH = "44"
    QUESTIONMARK = "44 using shift down"
    EXCLAIMATIONMARK = "18 using shift down"
    AT_THERATE = "19 using shift down"
    HASH = "20 using shift down"
    DOLLAR = "21 using shift down"
    PERCENT = "23 using shift down"
    CARROT = "22 using shift down"
    AMPERSAND = "26 using shift down"
    ASTERISK = "28 using shift down"
    PARENTHESES_OPEN = "25 using shift down"
    PARENTHESIS_CLOSE = "29 using shift down"
    SUBTRACT = "27"
    ADD = "24 using shift down"
    UNDERSCORE = "27 using shift down"
    EQUAL = "24"
