from .Requests import DetectLang
from .Requests import SemanticAnalysis
from .Requests import Summarize
from .Requests import TextsSimilarity
from .Requests import UrlAnalysis
from .Requests import SyntaxAnalysis
from .Requests import KeyPhrasesExtraction
from .Requests import PhraseMatcher
from .Requests import RuleBasedMatcher
