# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gv_protobuf/data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gv_protobuf import location_pb2 as gv__protobuf_dot_location__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gv_protobuf/data.proto',
  package='gv_protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x16gv_protobuf/data.proto\x12\x0bgv_protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1agv_protobuf/location.proto\"\x97\x01\n\rClusterSample\x12%\n\x07\x63luster\x18\x01 \x01(\x0b\x32\x14.gv_protobuf.Cluster\x12\x32\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32$.gv_protobuf.ClusterSample.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"h\n\x0b\x43lusterData\x12*\n\x06sample\x18\x01 \x03(\x0b\x32\x1a.gv_protobuf.ClusterSample\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x83\x01\n\x08\x43pSample\x12\x1b\n\x02\x63p\x18\x01 \x01(\x0b\x32\x0f.gv_protobuf.Cp\x12-\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x1f.gv_protobuf.CpSample.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"^\n\x06\x43pData\x12%\n\x06sample\x18\x01 \x03(\x0b\x32\x15.gv_protobuf.CpSample\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x97\x01\n\rSectionSample\x12%\n\x07section\x18\x01 \x01(\x0b\x32\x14.gv_protobuf.Section\x12\x32\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32$.gv_protobuf.SectionSample.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"h\n\x0bSectionData\x12*\n\x06sample\x18\x01 \x03(\x0b\x32\x1a.gv_protobuf.SectionSample\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x8b\x01\n\nZoneSample\x12\x1f\n\x04zone\x18\x01 \x01(\x0b\x32\x11.gv_protobuf.Zone\x12/\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32!.gv_protobuf.ZoneSample.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"b\n\x08ZoneData\x12\'\n\x06sample\x18\x01 \x03(\x0b\x32\x17.gv_protobuf.ZoneSample\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,gv__protobuf_dot_location__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLUSTERSAMPLE_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='gv_protobuf.ClusterSample.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gv_protobuf.ClusterSample.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='gv_protobuf.ClusterSample.DataEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=252,
)

_CLUSTERSAMPLE = _descriptor.Descriptor(
  name='ClusterSample',
  full_name='gv_protobuf.ClusterSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='gv_protobuf.ClusterSample.cluster', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='gv_protobuf.ClusterSample.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CLUSTERSAMPLE_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=252,
)


_CLUSTERDATA = _descriptor.Descriptor(
  name='ClusterData',
  full_name='gv_protobuf.ClusterData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample', full_name='gv_protobuf.ClusterData.sample', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='gv_protobuf.ClusterData.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=358,
)


_CPSAMPLE_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='gv_protobuf.CpSample.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gv_protobuf.CpSample.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='gv_protobuf.CpSample.DataEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=252,
)

_CPSAMPLE = _descriptor.Descriptor(
  name='CpSample',
  full_name='gv_protobuf.CpSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cp', full_name='gv_protobuf.CpSample.cp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='gv_protobuf.CpSample.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CPSAMPLE_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=492,
)


_CPDATA = _descriptor.Descriptor(
  name='CpData',
  full_name='gv_protobuf.CpData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample', full_name='gv_protobuf.CpData.sample', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='gv_protobuf.CpData.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=588,
)


_SECTIONSAMPLE_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='gv_protobuf.SectionSample.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gv_protobuf.SectionSample.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='gv_protobuf.SectionSample.DataEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=252,
)

_SECTIONSAMPLE = _descriptor.Descriptor(
  name='SectionSample',
  full_name='gv_protobuf.SectionSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='section', full_name='gv_protobuf.SectionSample.section', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='gv_protobuf.SectionSample.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SECTIONSAMPLE_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=742,
)


_SECTIONDATA = _descriptor.Descriptor(
  name='SectionData',
  full_name='gv_protobuf.SectionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample', full_name='gv_protobuf.SectionData.sample', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='gv_protobuf.SectionData.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=744,
  serialized_end=848,
)


_ZONESAMPLE_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='gv_protobuf.ZoneSample.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gv_protobuf.ZoneSample.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='gv_protobuf.ZoneSample.DataEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=252,
)

_ZONESAMPLE = _descriptor.Descriptor(
  name='ZoneSample',
  full_name='gv_protobuf.ZoneSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone', full_name='gv_protobuf.ZoneSample.zone', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='gv_protobuf.ZoneSample.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ZONESAMPLE_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=851,
  serialized_end=990,
)


_ZONEDATA = _descriptor.Descriptor(
  name='ZoneData',
  full_name='gv_protobuf.ZoneData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample', full_name='gv_protobuf.ZoneData.sample', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='gv_protobuf.ZoneData.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=992,
  serialized_end=1090,
)

_CLUSTERSAMPLE_DATAENTRY.containing_type = _CLUSTERSAMPLE
_CLUSTERSAMPLE.fields_by_name['cluster'].message_type = gv__protobuf_dot_location__pb2._CLUSTER
_CLUSTERSAMPLE.fields_by_name['data'].message_type = _CLUSTERSAMPLE_DATAENTRY
_CLUSTERDATA.fields_by_name['sample'].message_type = _CLUSTERSAMPLE
_CLUSTERDATA.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CPSAMPLE_DATAENTRY.containing_type = _CPSAMPLE
_CPSAMPLE.fields_by_name['cp'].message_type = gv__protobuf_dot_location__pb2._CP
_CPSAMPLE.fields_by_name['data'].message_type = _CPSAMPLE_DATAENTRY
_CPDATA.fields_by_name['sample'].message_type = _CPSAMPLE
_CPDATA.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SECTIONSAMPLE_DATAENTRY.containing_type = _SECTIONSAMPLE
_SECTIONSAMPLE.fields_by_name['section'].message_type = gv__protobuf_dot_location__pb2._SECTION
_SECTIONSAMPLE.fields_by_name['data'].message_type = _SECTIONSAMPLE_DATAENTRY
_SECTIONDATA.fields_by_name['sample'].message_type = _SECTIONSAMPLE
_SECTIONDATA.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ZONESAMPLE_DATAENTRY.containing_type = _ZONESAMPLE
_ZONESAMPLE.fields_by_name['zone'].message_type = gv__protobuf_dot_location__pb2._ZONE
_ZONESAMPLE.fields_by_name['data'].message_type = _ZONESAMPLE_DATAENTRY
_ZONEDATA.fields_by_name['sample'].message_type = _ZONESAMPLE
_ZONEDATA.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ClusterSample'] = _CLUSTERSAMPLE
DESCRIPTOR.message_types_by_name['ClusterData'] = _CLUSTERDATA
DESCRIPTOR.message_types_by_name['CpSample'] = _CPSAMPLE
DESCRIPTOR.message_types_by_name['CpData'] = _CPDATA
DESCRIPTOR.message_types_by_name['SectionSample'] = _SECTIONSAMPLE
DESCRIPTOR.message_types_by_name['SectionData'] = _SECTIONDATA
DESCRIPTOR.message_types_by_name['ZoneSample'] = _ZONESAMPLE
DESCRIPTOR.message_types_by_name['ZoneData'] = _ZONEDATA

ClusterSample = _reflection.GeneratedProtocolMessageType('ClusterSample', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _CLUSTERSAMPLE_DATAENTRY,
    __module__ = 'gv_protobuf.data_pb2'
    # @@protoc_insertion_point(class_scope:gv_protobuf.ClusterSample.DataEntry)
    ))
  ,
  DESCRIPTOR = _CLUSTERSAMPLE,
  __module__ = 'gv_protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:gv_protobuf.ClusterSample)
  ))
_sym_db.RegisterMessage(ClusterSample)
_sym_db.RegisterMessage(ClusterSample.DataEntry)

ClusterData = _reflection.GeneratedProtocolMessageType('ClusterData', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERDATA,
  __module__ = 'gv_protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:gv_protobuf.ClusterData)
  ))
_sym_db.RegisterMessage(ClusterData)

CpSample = _reflection.GeneratedProtocolMessageType('CpSample', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _CPSAMPLE_DATAENTRY,
    __module__ = 'gv_protobuf.data_pb2'
    # @@protoc_insertion_point(class_scope:gv_protobuf.CpSample.DataEntry)
    ))
  ,
  DESCRIPTOR = _CPSAMPLE,
  __module__ = 'gv_protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:gv_protobuf.CpSample)
  ))
_sym_db.RegisterMessage(CpSample)
_sym_db.RegisterMessage(CpSample.DataEntry)

CpData = _reflection.GeneratedProtocolMessageType('CpData', (_message.Message,), dict(
  DESCRIPTOR = _CPDATA,
  __module__ = 'gv_protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:gv_protobuf.CpData)
  ))
_sym_db.RegisterMessage(CpData)

SectionSample = _reflection.GeneratedProtocolMessageType('SectionSample', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _SECTIONSAMPLE_DATAENTRY,
    __module__ = 'gv_protobuf.data_pb2'
    # @@protoc_insertion_point(class_scope:gv_protobuf.SectionSample.DataEntry)
    ))
  ,
  DESCRIPTOR = _SECTIONSAMPLE,
  __module__ = 'gv_protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:gv_protobuf.SectionSample)
  ))
_sym_db.RegisterMessage(SectionSample)
_sym_db.RegisterMessage(SectionSample.DataEntry)

SectionData = _reflection.GeneratedProtocolMessageType('SectionData', (_message.Message,), dict(
  DESCRIPTOR = _SECTIONDATA,
  __module__ = 'gv_protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:gv_protobuf.SectionData)
  ))
_sym_db.RegisterMessage(SectionData)

ZoneSample = _reflection.GeneratedProtocolMessageType('ZoneSample', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _ZONESAMPLE_DATAENTRY,
    __module__ = 'gv_protobuf.data_pb2'
    # @@protoc_insertion_point(class_scope:gv_protobuf.ZoneSample.DataEntry)
    ))
  ,
  DESCRIPTOR = _ZONESAMPLE,
  __module__ = 'gv_protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:gv_protobuf.ZoneSample)
  ))
_sym_db.RegisterMessage(ZoneSample)
_sym_db.RegisterMessage(ZoneSample.DataEntry)

ZoneData = _reflection.GeneratedProtocolMessageType('ZoneData', (_message.Message,), dict(
  DESCRIPTOR = _ZONEDATA,
  __module__ = 'gv_protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:gv_protobuf.ZoneData)
  ))
_sym_db.RegisterMessage(ZoneData)


_CLUSTERSAMPLE_DATAENTRY.has_options = True
_CLUSTERSAMPLE_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_CPSAMPLE_DATAENTRY.has_options = True
_CPSAMPLE_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_SECTIONSAMPLE_DATAENTRY.has_options = True
_SECTIONSAMPLE_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_ZONESAMPLE_DATAENTRY.has_options = True
_ZONESAMPLE_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
