# coding: utf-8

"""
    ARLAS CITY API

    ARLAS-city content manager

    OpenAPI spec version: 0.1.0
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import arlas_city_api_python
from arlas_city_api_python.rest import ApiException
from arlas_city_api_python.apis.data_api import DataApi


class TestDataApi(unittest.TestCase):
    """ DataApi unit test stubs """

    def setUp(self):
        self.api = arlas_city_api_python.apis.data_api.DataApi()

    def tearDown(self):
        pass

    def test_delete_archive(self):
        """
        Test case for delete_archive

        Delete GTFS archive.
        """
        pass

    def test_get_archive(self):
        """
        Test case for get_archive

        Delete GTFS archive.
        """
        pass

    def test_get_archives(self):
        """
        Test case for get_archives

        List of GTFS archives.
        """
        pass

    def test_post_archive(self):
        """
        Test case for post_archive

        Upload a GTFS archive.
        """
        pass


if __name__ == '__main__':
    unittest.main()
