# coding: utf-8

"""
    ARLAS persistence API

    persistence REST services

    OpenAPI spec version: 12.0.1
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import arlas_persistence_api_python
from arlas_persistence_api_python.rest import ApiException
from arlas_persistence_api_python.apis.persistence_api import PersistenceApi


class TestPersistenceApi(unittest.TestCase):
    """ PersistenceApi unit test stubs """

    def setUp(self):
        self.api = arlas_persistence_api_python.apis.persistence_api.PersistenceApi()

    def tearDown(self):
        pass

    def test_create(self):
        """
        Test case for create

        Store a new piece of data for the provided key (auto generate id)
        """
        pass

    def test_delete(self):
        """
        Test case for delete

        Delete an entry given its key and id.
        """
        pass

    def test_get(self):
        """
        Test case for get

        Fetch an entry given its key and id.
        """
        pass

    def test_list(self):
        """
        Test case for list

        Fetch a list of data related to a key.
        """
        pass

    def test_update(self):
        """
        Test case for update

        Update an existing value.
        """
        pass


if __name__ == '__main__':
    unittest.main()
