"""Example module that plugs into dhm_module_base using the .plugins entrypoint."""
__version__ = "0.0.1"
__description__ = "Example that plugs into dhm_module_base"
__author__ = "Nicolai Mogensen"
__email__ = "nicolai@septima.dk"
__uri__ = "https://github.com/Kortforsyningen/dhm-module-example"
__license__ = "Licensed under the MIT license"
