from faker import Faker
from model_bakery.recipe import Recipe, seq
from edc_constants.constants import NOT_APPLICABLE, YES, NO, TRUE, FALSE
from edc_utils import get_utcnow

fake = Faker()

coronaviruskap = Recipe(
    "sarscov2.coronaviruskap",
    # report_datetime=get_utcnow(),
    hiv_pos=YES,
    hiv_pos_year=2006,
    hiv_year_started_art=2006,
    hiv_missed_doses=0,
    diabetic=NO,
    diabetic_dx_year=None,
    diabetic_on_meds=NOT_APPLICABLE,
    diabetic_missed_doses=None,
    hypertensive=NO,
    hypertensive_dx_year=None,
    hypertensive_on_meds=NOT_APPLICABLE,
    hypertensive_missed_doses=None,
    weight=65,
    height=120,
    sys_blood_pressure=120,
    dia_blood_pressure=85,
    married=YES,
    employment_status="unemployed",
    household_size=3,
    nights_away=4,
    employment="labourer",
    employment_other=None,
    education="secondary",
    health_insurance="private",
    health_insurance_other=None,
    personal_health_opinion="good",
    perceived_threat=8,
    corona_concern="somewhat",
    personal_infection_likelihood="very",
    family_infection_likelihood="very",
    perc_die=50,
    perc_mild_symptom=50,
    spread_droplets=TRUE,
    spread_touch=TRUE,
    spread_sick=TRUE,
    spread_asymptomatic=TRUE,
    severity_age=TRUE,
    severity_hiv=TRUE,
    severity_diabetes_hypertension=TRUE,
    hot_climate=TRUE,
    lives_on_materials=TRUE,
    spread_touch2=TRUE,
    symptoms_fever=TRUE,
    symptoms_headache=TRUE,
    symptoms_dry_cough=TRUE,
    symptoms_body_aches=TRUE,
    symptoms_smell=TRUE,
    symptoms_breathing=TRUE,
    know_other_symptoms=NO,
    symptoms_other=None,
    hot_drinks=FALSE,
    alcohol=FALSE,
    wash_hands=TRUE,
    hand_sanitizer=TRUE,
    avoid_crowds=TRUE,
    face_masks=TRUE,
    stay_indoors=TRUE,
    social_distance=TRUE,
    stay_home="unlikely",
    visit_clinic="unlikely",
    call_nurse="unlikely",
    take_meds="unlikely",
    stop_chronic_meds="unlikely",
    visit_religious="unlikely",
    visit_traditional="unlikely",
)
