
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-14T18:17:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "be32bfefe18f57c45de32acb547f1817c0ed6e0d",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
