
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-11T13:16:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e841f00fd2cfac91fd6fdd2f8bee9da3a9d44e03",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
