__title__ = "aamras"
__description__ = "Library for headless browser manipulation"
__url__ = "https://github.com/allekmott/"
__version__ = "0.0.2"
__author__ = "Allek Mott"
__author_email__ = "allekmott@gmail.com"
__license__ = "GPLv3"
