
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-14T18:02:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2cfa16ac623ac76b67165f55e8fc0b6db61399cb",
 "version": "0.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
