
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-12T16:07:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c99dd02c4517f62e92df082d1a81c2a555f8d9e",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
