#Language iso 1 - json
language_alpa_1 = {
  "aa": ["aar", "Afaraf"],
  "ab": ["abk", "аҧсуа бызәа, аҧсшәа"],
  "af": ["afr", "Afrikaans"],
  "ak": ["aka", "Akan"],
  "am": ["amh", "አማርኛ"],
  "ar": ["ara", "العربية"],
  "an": ["arg", "aragonés"],
  "as": ["asm", "অসমীয়া"],
  "av": ["ava", "авар м]ацӀ, магӀарул мацӀ"],
  "ae": ["ave", "avesta"],
  "ay": ["aym", "aymar"],
  "az": ["aze", "Azərbaycan"],
  "ba": ["bak", "башҡорт теле"],
  "bm": ["bam", "bamanankan"],
  "be": ["bel", "беларуская мова"],
  "bn": ["ben", "বাংলা"],
  "bh": ["bih", "भोजपुरी"],
  "bi": ["bis", "Bislama"],
  "bo": ["tib", "བོད་ཡིག"],
  "bs": ["bos", "bosanski jezik"],
  "br": ["bre", "brezhoneg"],
  "bg": ["bul", "български език"],
  "ca": ["cat", "català, valencià"],
  "cs": ["cze", "čeština, český jazyk"],
  "ch": ["cha", "Chamoru"],
  "ce": ["che", "нохчийн мотт"],
  "cu": ["chu", "ѩзыкъ словѣньскъ"],
  "cv": ["chv", "чӑваш чӗлхи"],
  "kw": ["cor", "Kernewek"],
  "co": ["cos", "corsu, lingua corsa"],
  "cr": ["cre", "ᓀᐦᐃᔭᐤ (Nehiyāw)"],
  "cy": ["wel", "Cymraeg"],
  "da": ["dan", "dansk"],
  "de": ["ger", "Deutsch"],
  "dv": ["div", "ދިވެހި"],
  "dz": ["dzo", "རྫོང་ཁ"],
  "el": ["gre", "ελληνικά"],
  "en": ["eng", "English"],
  "en-US": ["eng", "USA"],
  "eo": ["epo", "Esperanto"],
  "et": ["est", "eesti"],
  "eu": ["baq", "euskara, euskera"],
  "ee": ["ewe", "Eʋegbe"],
  "fo": ["fao", "føroyskt"],
  "fa": ["per", "فارسی"],
  "fj": ["fij", "vosa Vakaviti"],
  "fl": ["fil", "Pilipino"],
  "fi": ["fin", "suomi, suomen kieli"],
  "fr": ["fre", "français, langue française"],
  "fy": ["fry", "Frysk"],
  "ff": ["ful", "Fulfulde, Pulaar, Pular"],
  "gd": ["gla", "Gàidhlig"],
  "ga": ["gle", "Gaeilge"],
  "gl": ["glg", "Galego"],
  "gv": ["glv", "Gaelg, Gailck"],
  "gn": ["grn", "Avañe'ẽ"],
  "gu": ["guj", "ગુજરાતી"],
  "ht": ["hat", "Kreyòl ayisyen"],
  "ha": ["hau", "(Hausa) هَوُسَ"],
  "sh": ["shn", "српскохрватски/hrvatskosrpski"],
  "he": ["heb", "עברית"],
  "hz": ["her", "Otjiherero"],
  "hi": ["hin", "हिन्दी, हिंदी"],
  "ho": ["hmo", "Hiri Motu"],
  "hr": ["hrv", "hrvatski jezik"],
  "hu": ["hun", "magyar"],
  "hy": ["arm", "Հայերեն"],
  "ig": ["ibo", "Asụsụ Igbo"],
  "io": ["ido", "Ido"],
  "ii": ["iii", "ꆈꌠ꒿ Nuosuhxop"],
  "iu": ["iku", "ᐃᓄᒃᑎᑐᑦ"],
  "ie": ["ile", "Originally called Occidental; then Interlingue after WWII"],
  "ia": ["ina", "Interlingua"],
  "id": ["ind", "Bahasa Indonesia"],
  "ik": ["ipk", "Iñupiaq, Iñupiatun"],
  "is": ["ice", "Íslenska"],
  "it": ["ita", "Italiano"],
  "jv": ["jav", "ꦧꦱꦗꦮ, Basa Jawa"],
  "ja": ["jpn", "日本語 (にほんご)"],
  "kl": ["kal", "kalaallisut, kalaallit oqaasii"],
  "kn": ["kan", "ಕನ್ನಡ"],
  "ks": ["kas", "कश्मीरी, كشميري‎"],
  "ka": ["geo", "ქართული"],
  "kr": ["kau", "Kanuri"],
  "kk": ["kaz", "қазақ тілі"],
  "km": ["khm", "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ"],
  "ki": ["kik", "Gĩkũyũ"],
  "rw": ["kin", "Ikinyarwanda"],
  "ky": ["kir", "Кыргызча, Кыргыз тили"],
  "kv": ["kom", "коми кыв"],
  "kg": ["kon", "Kikongo"],
  "ko": ["kor", "한국어"],
  "kj": ["kua", "Kuanyama"],
  "ku": ["kur", "Kurdî, كوردی‎"],
  "lo": ["lao", "ພາສາລາວ"],
  "la": ["lat", "latine, lingua latina"],
  "lv": ["lav", "latviešu valoda"],
  "li": ["lim", "Limburgs"],
  "ln": ["lin", "Lingála"],
  "lt": ["lit", "lietuvių kalba"],
  "lb": ["ltz", "Lëtzebuergesch"],
  "lu": ["lub", "Kiluba"],
  "lg": ["lug", "Luganda"],
  "mh": ["mah", "Kajin M̧ajeļ"],
  "ml": ["mal", "മലയാളം"],
  "mr": ["mar", "मराठी"],
  "mk": ["mac", "македонски јазик"],
  "mg": ["mlg", "Malagasy"],
  "mt": ["mlt", "Malti"],
  "mn": ["mon", "Монгол хэл"],
  "mi": ["mao", "te reo Māori"],
  "ms": ["may", "Bahasa Melayu, بهاس ملايو‎"],
  "my": ["bur", "ဗမာစာ"],
  "na": ["nau", "Dorerin Naoero"],
  "nv": ["nav", "Diné bizaad"],
  "nr": ["nbl", "isiNdebele"],
  "nd": ["nde", "isiNdebele"],
  "ng": ["ndo", "Owambo"],
  "ne": ["nep", "नेपाली"],
  "nl": ["dut", "Nederlands, Vlaams"],
  "nn": ["nno", "Norsk Nynorsk"],
  "nb": ["nob", "Norsk Bokmål"],
  "no": ["nor", "Norsk"],
  "ny": ["nya", "chiCheŵa, chinyanja"],
  "oc": ["oci", "occitan, lenga dòc"],
  "oj": ["oji", "ᐊᓂᔑᓈᐯᒧᐎᓐ"],
  "or": ["ori", "ଓଡ଼ିଆ"],
  "om": ["orm", "Afaan Oromoo"],
  "os": ["oss", "ирон æвзаг"],
  "pa": ["pan", "ਪੰਜਾਬੀ"],
  "pi": ["pli", "पाऴि"],
  "pl": ["pol", "język polski, polszczyzna"],
  "pt": ["por", "Português"],
  "ps": ["pus", "پښتو"],
  "qu": ["que", "Runa Simi, Kichwa"],
  "rm": ["roh", "Rumantsch Grischun"],
  "ro": ["rum", "Română"],
  "rn": ["run", "Ikirundi"],
  "ru": ["rus", "русский"],
  "sg": ["sag", "yângâ tî sängö"],
  "sa": ["san", "संस्कृतम्"],
  "si": ["sin", "සිංහල"],
  "sl": ["slv", "Slovenski Jezik, Slovenščina"],
  "se": ["sme", "Davvisámegiella"],
  "sm": ["smo", "gagana fa'a Samoa"],
  "sn": ["sna", "chiShona"],
  "sd": ["snd", "सिन्धी, سنڌي، سندھی‎"],
  "so": ["som", "Soomaaliga, af Soomaali"],
  "st": ["sot", "Sesotho"],
  "es": ["spa", "Español"],
  "sq": ["alb", "Shqip"],
  "sc": ["srd", "sardu"],
  "sr": ["srp", "српски језик"],
  "ss": ["ssw", "SiSwati"],
  "su": ["sun", "Basa Sunda"],
  "sw": ["swa", "Kiswahili"],
  "sv": ["swe", "Svenska"],
  "ty": ["tah", "Reo Tahiti"],
  "ta": ["tam", "தமிழ்"],
  "tt": ["tat", "татар теле, tatar tele"],
  "te": ["tel", "తెలుగు"],
  "tg": ["tgk", "тоҷикӣ, toçikī, تاجیکی‎"],
  "tl": ["tgl", "Wikang Tagalog"],
  "th": ["tha", "ไทย"],
  "ti": ["tir", "ትግርኛ"],
  "to": ["ton", "Faka Tonga"],
  "tn": ["tsn", "Setswana"],
  "ts": ["tso", "Xitsonga"],
  "tk": ["tuk", "Türkmen, Түркмен"],
  "tr": ["tur", "Türkçe"],
  "tw": ["twi", "Twi"],
  "ug": ["uig", "ئۇيغۇرچە‎, Uyghurche"],
  "uk": ["ukr", "Українська"],
  "ur": ["urd", "اردو"],
  "uz": ["uzb", "Oʻzbek, Ўзбек, أۇزبېك‎"],
  "ve": ["ven", "Tshivenḓa"],
  "vi": ["vie", "Tiếng Việt"],
  "vo": ["vol", "Volapük"],
  "wa": ["wln", "Walon"],
  "wo": ["wol", "Wollof"],
  "xh": ["xho", "isiXhosa"],
  "yi": ["yid", "אידיש"],
  "yo": ["yor", "Yorùbá"],
  "za": ["zha", "Saɯ cueŋƅ, Saw cuengh"],
  "zh": ["chi", "中文(Zhōngwén), 汉语, 漢語"],
  "zu": ["zul", "isiZulu"],
  "fr-CA": ["fra-CA", "français, langue française"]
  }

language_alpa_3 = {} #Language  iso 3 - json
for key,value in language_alpa_1.items():
   
    new_key = value[0]
    new_value = [key,value[1]]
    language_alpa_3[new_key] = new_value






