
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-14T11:01:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dcd08c71a4e0c221cfda717d73d39ddfe9f81ce7",
 "version": "v0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
