# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\main_window.ui',
# licensing of 'C:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\main_window.ui' applies.
#
# Created: Fri May  8 09:42:20 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/joulescope/resources/icon_64x64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        mainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDeveloper = QtWidgets.QAction(mainWindow)
        self.actionDeveloper.setCheckable(True)
        self.actionDeveloper.setObjectName("actionDeveloper")
        self.actionDisable = QtWidgets.QAction(mainWindow)
        self.actionDisable.setObjectName("actionDisable")
        self.actionPlay = QtWidgets.QAction(mainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtWidgets.QAction(mainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionRecord = QtWidgets.QAction(mainWindow)
        self.actionRecord.setObjectName("actionRecord")
        self.actionOpen = QtWidgets.QAction(mainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(mainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionPreferences = QtWidgets.QAction(mainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUsbInrush = QtWidgets.QAction(mainWindow)
        self.actionUsbInrush.setObjectName("actionUsbInrush")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClearEnergy = QtWidgets.QAction(mainWindow)
        self.actionClearEnergy.setObjectName("actionClearEnergy")
        self.actionCredits = QtWidgets.QAction(mainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.actionGettingStarted = QtWidgets.QAction(mainWindow)
        self.actionGettingStarted.setObjectName("actionGettingStarted")
        self.actionUsersGuide = QtWidgets.QAction(mainWindow)
        self.actionUsersGuide.setObjectName("actionUsersGuide")
        self.actionViewLogs = QtWidgets.QAction(mainWindow)
        self.actionViewLogs.setObjectName("actionViewLogs")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionGettingStarted)
        self.menuHelp.addAction(self.actionUsersGuide)
        self.menuHelp.addAction(self.actionViewLogs)
        self.menuHelp.addAction(self.actionCredits)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionClearEnergy)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtWidgets.QApplication.translate("mainWindow", "Joulescope", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("mainWindow", "&File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("mainWindow", "&View", None, -1))
        self.menuDevice.setTitle(QtWidgets.QApplication.translate("mainWindow", "&Device", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("mainWindow", "&Help", None, -1))
        self.menuTools.setTitle(QtWidgets.QApplication.translate("mainWindow", "&Tools", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("mainWindow", "E&xit", None, -1))
        self.actionExit.setIconText(QtWidgets.QApplication.translate("mainWindow", "Exit", None, -1))
        self.actionDeveloper.setText(QtWidgets.QApplication.translate("mainWindow", "Developer", None, -1))
        self.actionDisable.setText(QtWidgets.QApplication.translate("mainWindow", "Disable", None, -1))
        self.actionPlay.setText(QtWidgets.QApplication.translate("mainWindow", "Play", None, -1))
        self.actionStop.setText(QtWidgets.QApplication.translate("mainWindow", "Stop", None, -1))
        self.actionRecord.setText(QtWidgets.QApplication.translate("mainWindow", "Record", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("mainWindow", "&Open", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("mainWindow", "&Close", None, -1))
        self.actionPreferences.setText(QtWidgets.QApplication.translate("mainWindow", "Preferences", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("mainWindow", "&About", None, -1))
        self.actionUsbInrush.setText(QtWidgets.QApplication.translate("mainWindow", "USB Inrush", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("mainWindow", "&Save", None, -1))
        self.actionClearEnergy.setText(QtWidgets.QApplication.translate("mainWindow", "Clear &Energy", None, -1))
        self.actionCredits.setText(QtWidgets.QApplication.translate("mainWindow", "Credits", None, -1))
        self.actionGettingStarted.setText(QtWidgets.QApplication.translate("mainWindow", "Getting Started", None, -1))
        self.actionUsersGuide.setText(QtWidgets.QApplication.translate("mainWindow", "User\'s Guide", None, -1))
        self.actionViewLogs.setText(QtWidgets.QApplication.translate("mainWindow", "View logs...", None, -1))

from joulescope_ui import joulescope_rc
