# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\preferences_dialog.ui',
# licensing of 'C:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\preferences_dialog.ui' applies.
#
# Created: Fri May  8 09:42:20 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(660, 388)
        PreferencesDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profileWidget = QtWidgets.QWidget(PreferencesDialog)
        self.profileWidget.setObjectName("profileWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.profileWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.profileLabel = QtWidgets.QLabel(self.profileWidget)
        self.profileLabel.setObjectName("profileLabel")
        self.horizontalLayout_3.addWidget(self.profileLabel)
        self.profileComboBox = QtWidgets.QComboBox(self.profileWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileComboBox.sizePolicy().hasHeightForWidth())
        self.profileComboBox.setSizePolicy(sizePolicy)
        self.profileComboBox.setObjectName("profileComboBox")
        self.horizontalLayout_3.addWidget(self.profileComboBox)
        self.profileActivateButton = QtWidgets.QPushButton(self.profileWidget)
        self.profileActivateButton.setObjectName("profileActivateButton")
        self.horizontalLayout_3.addWidget(self.profileActivateButton)
        self.profileResetButton = QtWidgets.QPushButton(self.profileWidget)
        self.profileResetButton.setObjectName("profileResetButton")
        self.horizontalLayout_3.addWidget(self.profileResetButton)
        self.profileNewButton = QtWidgets.QPushButton(self.profileWidget)
        self.profileNewButton.setObjectName("profileNewButton")
        self.horizontalLayout_3.addWidget(self.profileNewButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.helpButton = QtWidgets.QPushButton(self.profileWidget)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout_3.addWidget(self.helpButton)
        self.verticalLayout.addWidget(self.profileWidget)
        self.widget = QtWidgets.QWidget(PreferencesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtWidgets.QTreeView(self.widget)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.horizontalLayout.addWidget(self.treeView)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.targetWidget = QtWidgets.QWidget()
        self.targetWidget.setGeometry(QtCore.QRect(0, 0, 307, 254))
        self.targetWidget.setObjectName("targetWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.targetWidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.scrollArea.setWidget(self.targetWidget)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.widget)
        self.buttonFrame = QtWidgets.QFrame(PreferencesDialog)
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.resetButton = QtWidgets.QPushButton(self.buttonFrame)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.cancelButton = QtWidgets.QPushButton(self.buttonFrame)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(self.buttonFrame)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_2.addWidget(self.okButton)
        self.verticalLayout.addWidget(self.buttonFrame)

        self.retranslateUi(PreferencesDialog)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(QtWidgets.QApplication.translate("PreferencesDialog", "Preferences", None, -1))
        self.profileLabel.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Profile", None, -1))
        self.profileComboBox.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "Select the profile to view and edit.", None, -1))
        self.profileActivateButton.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Activate the selected profile.</span></p><p>This action updates Joulescope UI to use the preferences in the selected profile.</p></body></html>", None, -1))
        self.profileActivateButton.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Activate", None, -1))
        self.profileResetButton.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Reset or erase the selected profile.</span></p><p>For the built-in profiles, <span style=\" font-weight:600;\">Reset</span> the profile to the factory defaults.  For custom profiles, <span style=\" font-weight:600;\">Erase</span> the profile so that it is no longer available.  You cannot erase the built-in profiles.</p></body></html>", None, -1))
        self.profileResetButton.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Reset", None, -1))
        self.profileNewButton.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "<html><head/><body><p>Create a new custom profile.</p></body></html>", None, -1))
        self.profileNewButton.setText(QtWidgets.QApplication.translate("PreferencesDialog", "New", None, -1))
        self.helpButton.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Help", None, -1))
        self.treeView.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "Select the Preferences Group to display.", None, -1))
        self.scrollArea.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "View and edit the Preferences for the selected Profile and Preference Group.", None, -1))
        self.resetButton.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Reset the Preferences for the selected Profile and Preferences Group.</span></p><p>This button only resets the Preferences that are currently shown in the right-hand side, and only for the selected Profile.  All other preference values are not changed.</p></body></html>", None, -1))
        self.resetButton.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Reset to Defaults", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Cancel", None, -1))
        self.okButton.setText(QtWidgets.QApplication.translate("PreferencesDialog", "OK", None, -1))

