
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-05-10T08:32:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2818e4aa1ecb0729242f11bbfe04d6c914eb9c24",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
