
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-17T19:18:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "871c839ef955dd48f57c0a025e8e0cfb4da6425b",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
