# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PSE_Design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1080, 428)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1000, 250))
        Dialog.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.PSE = QtWidgets.QTableWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSE.sizePolicy().hasHeightForWidth())
        self.PSE.setSizePolicy(sizePolicy)
        self.PSE.setMinimumSize(QtCore.QSize(800, 350))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PSE.setFont(font)
        self.PSE.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PSE.setAutoScrollMargin(16)
        self.PSE.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.PSE.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.PSE.setRowCount(10)
        self.PSE.setColumnCount(18)
        self.PSE.setObjectName("PSE")
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PSE.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(0, 17, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.PSE.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(1, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(1, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(1, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(1, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(1, 16, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(1, 17, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(2, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(2, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(2, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(2, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(2, 16, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(2, 17, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 16, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(3, 17, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 16, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(4, 17, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.PSE.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(210, 255, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 16, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(5, 17, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(6, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.PSE.setItem(6, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.PSE.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.PSE.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(8, 16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.PSE.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 134, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.PSE.setItem(9, 16, item)
        self.PSE.horizontalHeader().setVisible(True)
        self.PSE.horizontalHeader().setCascadingSectionResizes(True)
        self.PSE.horizontalHeader().setDefaultSectionSize(30)
        self.PSE.horizontalHeader().setHighlightSections(False)
        self.PSE.horizontalHeader().setMinimumSectionSize(33)
        self.PSE.horizontalHeader().setSortIndicatorShown(False)
        self.PSE.horizontalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.PSE, 1, 0, 1, 1)
        self.Choose_element = QtWidgets.QDialogButtonBox(Dialog)
        self.Choose_element.setOrientation(QtCore.Qt.Horizontal)
        self.Choose_element.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Choose_element.setObjectName("Choose_element")
        self.gridLayout.addWidget(self.Choose_element, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.Choose_element.accepted.connect(Dialog.accept)
        self.Choose_element.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PSE"))
        self.label.setText(_translate("Dialog", "Periodic Table of Elements"))
        __sortingEnabled = self.PSE.isSortingEnabled()
        self.PSE.setSortingEnabled(False)
        item = self.PSE.item(0, 0)
        item.setText(_translate("Dialog", "H"))
        item = self.PSE.item(0, 17)
        item.setText(_translate("Dialog", "He"))
        item = self.PSE.item(1, 0)
        item.setText(_translate("Dialog", "Li"))
        item = self.PSE.item(1, 1)
        item.setText(_translate("Dialog", "Be"))
        item = self.PSE.item(1, 12)
        item.setText(_translate("Dialog", "B"))
        item = self.PSE.item(1, 13)
        item.setText(_translate("Dialog", "C"))
        item = self.PSE.item(1, 14)
        item.setText(_translate("Dialog", "N"))
        item = self.PSE.item(1, 15)
        item.setText(_translate("Dialog", "O"))
        item = self.PSE.item(1, 16)
        item.setText(_translate("Dialog", "F"))
        item = self.PSE.item(1, 17)
        item.setText(_translate("Dialog", "Ne"))
        item = self.PSE.item(2, 0)
        item.setText(_translate("Dialog", "Na"))
        item = self.PSE.item(2, 1)
        item.setText(_translate("Dialog", "Mg"))
        item = self.PSE.item(2, 12)
        item.setText(_translate("Dialog", "Al"))
        item = self.PSE.item(2, 13)
        item.setText(_translate("Dialog", "Si"))
        item = self.PSE.item(2, 14)
        item.setText(_translate("Dialog", "P"))
        item = self.PSE.item(2, 15)
        item.setText(_translate("Dialog", "S"))
        item = self.PSE.item(2, 16)
        item.setText(_translate("Dialog", "Cl"))
        item = self.PSE.item(2, 17)
        item.setText(_translate("Dialog", "Ar"))
        item = self.PSE.item(3, 0)
        item.setText(_translate("Dialog", "K"))
        item = self.PSE.item(3, 1)
        item.setText(_translate("Dialog", "Ca"))
        item = self.PSE.item(3, 2)
        item.setText(_translate("Dialog", "Sc"))
        item = self.PSE.item(3, 3)
        item.setText(_translate("Dialog", "Ti"))
        item = self.PSE.item(3, 4)
        item.setText(_translate("Dialog", "V"))
        item = self.PSE.item(3, 5)
        item.setText(_translate("Dialog", "Cr"))
        item = self.PSE.item(3, 6)
        item.setText(_translate("Dialog", "Mn"))
        item = self.PSE.item(3, 7)
        item.setText(_translate("Dialog", "Fe"))
        item = self.PSE.item(3, 8)
        item.setText(_translate("Dialog", "Co"))
        item = self.PSE.item(3, 9)
        item.setText(_translate("Dialog", "Ni"))
        item = self.PSE.item(3, 10)
        item.setText(_translate("Dialog", "Cu"))
        item = self.PSE.item(3, 11)
        item.setText(_translate("Dialog", "Zn"))
        item = self.PSE.item(3, 12)
        item.setText(_translate("Dialog", "Ga"))
        item = self.PSE.item(3, 13)
        item.setText(_translate("Dialog", "Ge"))
        item = self.PSE.item(3, 14)
        item.setText(_translate("Dialog", "As"))
        item = self.PSE.item(3, 15)
        item.setText(_translate("Dialog", "Se"))
        item = self.PSE.item(3, 16)
        item.setText(_translate("Dialog", "Br"))
        item = self.PSE.item(3, 17)
        item.setText(_translate("Dialog", "Kr"))
        item = self.PSE.item(4, 0)
        item.setText(_translate("Dialog", "Rb"))
        item = self.PSE.item(4, 1)
        item.setText(_translate("Dialog", "Sr"))
        item = self.PSE.item(4, 2)
        item.setText(_translate("Dialog", "Y"))
        item = self.PSE.item(4, 3)
        item.setText(_translate("Dialog", "Zr"))
        item = self.PSE.item(4, 4)
        item.setText(_translate("Dialog", "Nb"))
        item = self.PSE.item(4, 5)
        item.setText(_translate("Dialog", "Mo"))
        item = self.PSE.item(4, 6)
        item.setText(_translate("Dialog", "Tc"))
        item = self.PSE.item(4, 7)
        item.setText(_translate("Dialog", "Ru"))
        item = self.PSE.item(4, 8)
        item.setText(_translate("Dialog", "Rh"))
        item = self.PSE.item(4, 9)
        item.setText(_translate("Dialog", "Pd"))
        item = self.PSE.item(4, 10)
        item.setText(_translate("Dialog", "Ag"))
        item = self.PSE.item(4, 11)
        item.setText(_translate("Dialog", "Cd"))
        item = self.PSE.item(4, 12)
        item.setText(_translate("Dialog", "In"))
        item = self.PSE.item(4, 13)
        item.setText(_translate("Dialog", "Sn"))
        item = self.PSE.item(4, 14)
        item.setText(_translate("Dialog", "Sb"))
        item = self.PSE.item(4, 15)
        item.setText(_translate("Dialog", "Te"))
        item = self.PSE.item(4, 16)
        item.setText(_translate("Dialog", "I"))
        item = self.PSE.item(4, 17)
        item.setText(_translate("Dialog", "Xe"))
        item = self.PSE.item(5, 0)
        item.setText(_translate("Dialog", "Cs"))
        item = self.PSE.item(5, 1)
        item.setText(_translate("Dialog", "Ba"))
        item = self.PSE.item(5, 2)
        item.setText(_translate("Dialog", "La"))
        item = self.PSE.item(5, 3)
        item.setText(_translate("Dialog", "Hf"))
        item = self.PSE.item(5, 4)
        item.setText(_translate("Dialog", "Ta"))
        item = self.PSE.item(5, 5)
        item.setText(_translate("Dialog", "W"))
        item = self.PSE.item(5, 6)
        item.setText(_translate("Dialog", "Re"))
        item = self.PSE.item(5, 7)
        item.setText(_translate("Dialog", "Os"))
        item = self.PSE.item(5, 8)
        item.setText(_translate("Dialog", "Ir"))
        item = self.PSE.item(5, 9)
        item.setText(_translate("Dialog", "Pt"))
        item = self.PSE.item(5, 10)
        item.setText(_translate("Dialog", "Au"))
        item = self.PSE.item(5, 11)
        item.setText(_translate("Dialog", "Hg"))
        item = self.PSE.item(5, 12)
        item.setText(_translate("Dialog", "Tl"))
        item = self.PSE.item(5, 13)
        item.setText(_translate("Dialog", "Pb"))
        item = self.PSE.item(5, 14)
        item.setText(_translate("Dialog", "Bi"))
        item = self.PSE.item(5, 15)
        item.setText(_translate("Dialog", "Po"))
        item = self.PSE.item(5, 16)
        item.setText(_translate("Dialog", "At"))
        item = self.PSE.item(5, 17)
        item.setText(_translate("Dialog", "Rn"))
        item = self.PSE.item(6, 0)
        item.setText(_translate("Dialog", "Fr"))
        item = self.PSE.item(6, 1)
        item.setText(_translate("Dialog", "Ra"))
        item = self.PSE.item(6, 2)
        item.setText(_translate("Dialog", "Ac"))
        item = self.PSE.item(6, 3)
        item.setText(_translate("Dialog", "Rf"))
        item = self.PSE.item(6, 4)
        item.setText(_translate("Dialog", "Db"))
        item = self.PSE.item(6, 5)
        item.setText(_translate("Dialog", "Sg"))
        item = self.PSE.item(6, 6)
        item.setText(_translate("Dialog", "Bh"))
        item = self.PSE.item(6, 7)
        item.setText(_translate("Dialog", "Hs"))
        item = self.PSE.item(6, 8)
        item.setText(_translate("Dialog", "Mt"))
        item = self.PSE.item(6, 9)
        item.setText(_translate("Dialog", "Ds"))
        item = self.PSE.item(6, 10)
        item.setText(_translate("Dialog", "Rg"))
        item = self.PSE.item(8, 2)
        item.setText(_translate("Dialog", "Lanthanoide"))
        item = self.PSE.item(8, 3)
        item.setText(_translate("Dialog", "Ce"))
        item = self.PSE.item(8, 4)
        item.setText(_translate("Dialog", "Pr"))
        item = self.PSE.item(8, 5)
        item.setText(_translate("Dialog", "Nd"))
        item = self.PSE.item(8, 6)
        item.setText(_translate("Dialog", "Pm"))
        item = self.PSE.item(8, 7)
        item.setText(_translate("Dialog", "Sm"))
        item = self.PSE.item(8, 8)
        item.setText(_translate("Dialog", "Eu"))
        item = self.PSE.item(8, 9)
        item.setText(_translate("Dialog", "Gd"))
        item = self.PSE.item(8, 10)
        item.setText(_translate("Dialog", "Tb"))
        item = self.PSE.item(8, 11)
        item.setText(_translate("Dialog", "Dy"))
        item = self.PSE.item(8, 12)
        item.setText(_translate("Dialog", "Ho"))
        item = self.PSE.item(8, 13)
        item.setText(_translate("Dialog", "Er"))
        item = self.PSE.item(8, 14)
        item.setText(_translate("Dialog", "Tm"))
        item = self.PSE.item(8, 15)
        item.setText(_translate("Dialog", "Yb"))
        item = self.PSE.item(8, 16)
        item.setText(_translate("Dialog", "Lu"))
        item = self.PSE.item(9, 2)
        item.setText(_translate("Dialog", "Actinoide"))
        item = self.PSE.item(9, 3)
        item.setText(_translate("Dialog", "Th"))
        item = self.PSE.item(9, 4)
        item.setText(_translate("Dialog", "Pa"))
        item = self.PSE.item(9, 5)
        item.setText(_translate("Dialog", "U"))
        item = self.PSE.item(9, 6)
        item.setText(_translate("Dialog", "Np"))
        item = self.PSE.item(9, 7)
        item.setText(_translate("Dialog", "Pu"))
        item = self.PSE.item(9, 8)
        item.setText(_translate("Dialog", "Am"))
        item = self.PSE.item(9, 9)
        item.setText(_translate("Dialog", "Cm"))
        item = self.PSE.item(9, 10)
        item.setText(_translate("Dialog", "Bk"))
        item = self.PSE.item(9, 11)
        item.setText(_translate("Dialog", "Cf"))
        item = self.PSE.item(9, 12)
        item.setText(_translate("Dialog", "Es"))
        item = self.PSE.item(9, 13)
        item.setText(_translate("Dialog", "Fm"))
        item = self.PSE.item(9, 14)
        item.setText(_translate("Dialog", "Md"))
        item = self.PSE.item(9, 15)
        item.setText(_translate("Dialog", "No"))
        item = self.PSE.item(9, 16)
        item.setText(_translate("Dialog", "Lr"))
        self.PSE.setSortingEnabled(__sortingEnabled)

