# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.star_api import StarApi  # noqa: E501
from dbpedia.rest import ApiException


class TestStarApi(unittest.TestCase):
    """StarApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.star_api.StarApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stars_get(self):
        """Test case for stars_get

        List all instances of Star  # noqa: E501
        """
        pass

    def test_stars_id_get(self):
        """Test case for stars_id_get

        Get a single Star by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
