# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.temple_api import TempleApi  # noqa: E501
from dbpedia.rest import ApiException


class TestTempleApi(unittest.TestCase):
    """TempleApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.temple_api.TempleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_temples_get(self):
        """Test case for temples_get

        List all instances of Temple  # noqa: E501
        """
        pass

    def test_temples_id_get(self):
        """Test case for temples_id_get

        Get a single Temple by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
