# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import dbpedia
from dbpedia.models.supreme_court_of_the_united_states_case import SupremeCourtOfTheUnitedStatesCase  # noqa: E501
from dbpedia.rest import ApiException

class TestSupremeCourtOfTheUnitedStatesCase(unittest.TestCase):
    """SupremeCourtOfTheUnitedStatesCase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SupremeCourtOfTheUnitedStatesCase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = dbpedia.models.supreme_court_of_the_united_states_case.SupremeCourtOfTheUnitedStatesCase()  # noqa: E501
        if include_optional :
            return SupremeCourtOfTheUnitedStatesCase(
                attorney_general = [
                    None
                    ], 
                description = [
                    '0'
                    ], 
                legal_article = [
                    '0'
                    ], 
                procedure = [
                    '0'
                    ], 
                label = [
                    '0'
                    ], 
                system_of_law = [
                    None
                    ], 
                type = [
                    '0'
                    ], 
                code_book = [
                    '0'
                    ], 
                decide_date = [
                    '0'
                    ], 
                ruling = [
                    '0'
                    ], 
                solicitor_general = [
                    None
                    ], 
                argue_date = [
                    '0'
                    ], 
                developer = [
                    None
                    ], 
                id = '0', 
                judge = [
                    None
                    ]
            )
        else :
            return SupremeCourtOfTheUnitedStatesCase(
        )

    def testSupremeCourtOfTheUnitedStatesCase(self):
        """Test SupremeCourtOfTheUnitedStatesCase"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
