# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.swarm_api import SwarmApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSwarmApi(unittest.TestCase):
    """SwarmApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.swarm_api.SwarmApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_swarms_get(self):
        """Test case for swarms_get

        List all instances of Swarm  # noqa: E501
        """
        pass

    def test_swarms_id_get(self):
        """Test case for swarms_id_get

        Get a single Swarm by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
