# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.canadian_football_player_api import CanadianFootballPlayerApi  # noqa: E501
from dbpedia.rest import ApiException


class TestCanadianFootballPlayerApi(unittest.TestCase):
    """CanadianFootballPlayerApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.canadian_football_player_api.CanadianFootballPlayerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_canadianfootballplayers_get(self):
        """Test case for canadianfootballplayers_get

        List all instances of CanadianFootballPlayer  # noqa: E501
        """
        pass

    def test_canadianfootballplayers_id_get(self):
        """Test case for canadianfootballplayers_id_get

        Get a single CanadianFootballPlayer by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
