# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.watermill_api import WatermillApi  # noqa: E501
from dbpedia.rest import ApiException


class TestWatermillApi(unittest.TestCase):
    """WatermillApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.watermill_api.WatermillApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_watermills_get(self):
        """Test case for watermills_get

        List all instances of Watermill  # noqa: E501
        """
        pass

    def test_watermills_id_get(self):
        """Test case for watermills_id_get

        Get a single Watermill by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
