# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.painting_api import PaintingApi  # noqa: E501
from dbpedia.rest import ApiException


class TestPaintingApi(unittest.TestCase):
    """PaintingApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.painting_api.PaintingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_paintings_get(self):
        """Test case for paintings_get

        List all instances of Painting  # noqa: E501
        """
        pass

    def test_paintings_id_get(self):
        """Test case for paintings_id_get

        Get a single Painting by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
