# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.gene_location_api import GeneLocationApi  # noqa: E501
from dbpedia.rest import ApiException


class TestGeneLocationApi(unittest.TestCase):
    """GeneLocationApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.gene_location_api.GeneLocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_genelocations_get(self):
        """Test case for genelocations_get

        List all instances of GeneLocation  # noqa: E501
        """
        pass

    def test_genelocations_id_get(self):
        """Test case for genelocations_id_get

        Get a single GeneLocation by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
