# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.prehistorical_period_api import PrehistoricalPeriodApi  # noqa: E501
from dbpedia.rest import ApiException


class TestPrehistoricalPeriodApi(unittest.TestCase):
    """PrehistoricalPeriodApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.prehistorical_period_api.PrehistoricalPeriodApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_prehistoricalperiods_get(self):
        """Test case for prehistoricalperiods_get

        List all instances of PrehistoricalPeriod  # noqa: E501
        """
        pass

    def test_prehistoricalperiods_id_get(self):
        """Test case for prehistoricalperiods_id_get

        Get a single PrehistoricalPeriod by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
