# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.television_personality_api import TelevisionPersonalityApi  # noqa: E501
from dbpedia.rest import ApiException


class TestTelevisionPersonalityApi(unittest.TestCase):
    """TelevisionPersonalityApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.television_personality_api.TelevisionPersonalityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_televisionpersonalitys_get(self):
        """Test case for televisionpersonalitys_get

        List all instances of TelevisionPersonality  # noqa: E501
        """
        pass

    def test_televisionpersonalitys_id_get(self):
        """Test case for televisionpersonalitys_id_get

        Get a single TelevisionPersonality by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
