# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.producer_api import ProducerApi  # noqa: E501
from dbpedia.rest import ApiException


class TestProducerApi(unittest.TestCase):
    """ProducerApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.producer_api.ProducerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_producers_get(self):
        """Test case for producers_get

        List all instances of Producer  # noqa: E501
        """
        pass

    def test_producers_id_get(self):
        """Test case for producers_id_get

        Get a single Producer by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
