# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.satellite_api import SatelliteApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSatelliteApi(unittest.TestCase):
    """SatelliteApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.satellite_api.SatelliteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_satellites_get(self):
        """Test case for satellites_get

        List all instances of Satellite  # noqa: E501
        """
        pass

    def test_satellites_id_get(self):
        """Test case for satellites_id_get

        Get a single Satellite by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
