# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.railway_line_api import RailwayLineApi  # noqa: E501
from dbpedia.rest import ApiException


class TestRailwayLineApi(unittest.TestCase):
    """RailwayLineApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.railway_line_api.RailwayLineApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_railwaylines_get(self):
        """Test case for railwaylines_get

        List all instances of RailwayLine  # noqa: E501
        """
        pass

    def test_railwaylines_id_get(self):
        """Test case for railwaylines_id_get

        Get a single RailwayLine by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
