# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.stream_api import StreamApi  # noqa: E501
from dbpedia.rest import ApiException


class TestStreamApi(unittest.TestCase):
    """StreamApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.stream_api.StreamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_streams_get(self):
        """Test case for streams_get

        List all instances of Stream  # noqa: E501
        """
        pass

    def test_streams_id_get(self):
        """Test case for streams_id_get

        Get a single Stream by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
