# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.team_member_api import TeamMemberApi  # noqa: E501
from dbpedia.rest import ApiException


class TestTeamMemberApi(unittest.TestCase):
    """TeamMemberApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.team_member_api.TeamMemberApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_teammembers_get(self):
        """Test case for teammembers_get

        List all instances of TeamMember  # noqa: E501
        """
        pass

    def test_teammembers_id_get(self):
        """Test case for teammembers_id_get

        Get a single TeamMember by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
