# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.religious_api import ReligiousApi  # noqa: E501
from dbpedia.rest import ApiException


class TestReligiousApi(unittest.TestCase):
    """ReligiousApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.religious_api.ReligiousApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_religiouss_get(self):
        """Test case for religiouss_get

        List all instances of Religious  # noqa: E501
        """
        pass

    def test_religiouss_id_get(self):
        """Test case for religiouss_id_get

        Get a single Religious by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
