# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.unknown_api import UnknownApi  # noqa: E501
from dbpedia.rest import ApiException


class TestUnknownApi(unittest.TestCase):
    """UnknownApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.unknown_api.UnknownApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_unknowns_get(self):
        """Test case for unknowns_get

        List all instances of Unknown  # noqa: E501
        """
        pass

    def test_unknowns_id_get(self):
        """Test case for unknowns_id_get

        Get a single Unknown by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
