# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.district_api import DistrictApi  # noqa: E501
from dbpedia.rest import ApiException


class TestDistrictApi(unittest.TestCase):
    """DistrictApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.district_api.DistrictApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_districts_get(self):
        """Test case for districts_get

        List all instances of District  # noqa: E501
        """
        pass

    def test_districts_id_get(self):
        """Test case for districts_id_get

        Get a single District by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
