# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.dam_api import DamApi  # noqa: E501
from dbpedia.rest import ApiException


class TestDamApi(unittest.TestCase):
    """DamApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.dam_api.DamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dams_get(self):
        """Test case for dams_get

        List all instances of Dam  # noqa: E501
        """
        pass

    def test_dams_id_get(self):
        """Test case for dams_id_get

        Get a single Dam by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
