# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.sculpture_api import SculptureApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSculptureApi(unittest.TestCase):
    """SculptureApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.sculpture_api.SculptureApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sculptures_get(self):
        """Test case for sculptures_get

        List all instances of Sculpture  # noqa: E501
        """
        pass

    def test_sculptures_id_get(self):
        """Test case for sculptures_id_get

        Get a single Sculpture by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
