# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.racing_driver_api import RacingDriverApi  # noqa: E501
from dbpedia.rest import ApiException


class TestRacingDriverApi(unittest.TestCase):
    """RacingDriverApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.racing_driver_api.RacingDriverApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_racingdrivers_get(self):
        """Test case for racingdrivers_get

        List all instances of RacingDriver  # noqa: E501
        """
        pass

    def test_racingdrivers_id_get(self):
        """Test case for racingdrivers_id_get

        Get a single RacingDriver by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
