# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.curler_api import CurlerApi  # noqa: E501
from dbpedia.rest import ApiException


class TestCurlerApi(unittest.TestCase):
    """CurlerApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.curler_api.CurlerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_curlers_get(self):
        """Test case for curlers_get

        List all instances of Curler  # noqa: E501
        """
        pass

    def test_curlers_id_get(self):
        """Test case for curlers_id_get

        Get a single Curler by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
