# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.human_gene_api import HumanGeneApi  # noqa: E501
from dbpedia.rest import ApiException


class TestHumanGeneApi(unittest.TestCase):
    """HumanGeneApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.human_gene_api.HumanGeneApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_humangenes_get(self):
        """Test case for humangenes_get

        List all instances of HumanGene  # noqa: E501
        """
        pass

    def test_humangenes_id_get(self):
        """Test case for humangenes_id_get

        Get a single HumanGene by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
