# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.clerical_administrative_region_api import ClericalAdministrativeRegionApi  # noqa: E501
from dbpedia.rest import ApiException


class TestClericalAdministrativeRegionApi(unittest.TestCase):
    """ClericalAdministrativeRegionApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.clerical_administrative_region_api.ClericalAdministrativeRegionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clericaladministrativeregions_get(self):
        """Test case for clericaladministrativeregions_get

        List all instances of ClericalAdministrativeRegion  # noqa: E501
        """
        pass

    def test_clericaladministrativeregions_id_get(self):
        """Test case for clericaladministrativeregions_id_get

        Get a single ClericalAdministrativeRegion by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
