# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.name_api import NameApi  # noqa: E501
from dbpedia.rest import ApiException


class TestNameApi(unittest.TestCase):
    """NameApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.name_api.NameApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_names_get(self):
        """Test case for names_get

        List all instances of Name  # noqa: E501
        """
        pass

    def test_names_id_get(self):
        """Test case for names_id_get

        Get a single Name by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
