# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.song_api import SongApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSongApi(unittest.TestCase):
    """SongApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.song_api.SongApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_songs_get(self):
        """Test case for songs_get

        List all instances of Song  # noqa: E501
        """
        pass

    def test_songs_id_get(self):
        """Test case for songs_id_get

        Get a single Song by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
