# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.journalist_api import JournalistApi  # noqa: E501
from dbpedia.rest import ApiException


class TestJournalistApi(unittest.TestCase):
    """JournalistApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.journalist_api.JournalistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_journalists_get(self):
        """Test case for journalists_get

        List all instances of Journalist  # noqa: E501
        """
        pass

    def test_journalists_id_get(self):
        """Test case for journalists_id_get

        Get a single Journalist by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
