# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.comic_api import ComicApi  # noqa: E501
from dbpedia.rest import ApiException


class TestComicApi(unittest.TestCase):
    """ComicApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.comic_api.ComicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_comics_get(self):
        """Test case for comics_get

        List all instances of Comic  # noqa: E501
        """
        pass

    def test_comics_id_get(self):
        """Test case for comics_id_get

        Get a single Comic by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
