# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import dbpedia
from dbpedia.models.academic_journal import AcademicJournal  # noqa: E501
from dbpedia.rest import ApiException

class TestAcademicJournal(unittest.TestCase):
    """AcademicJournal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AcademicJournal
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = dbpedia.models.academic_journal.AcademicJournal()  # noqa: E501
        if include_optional :
            return AcademicJournal(
                academic_discipline = [
                    None
                    ], 
                frequency_of_publication = [
                    '0'
                    ], 
                final_publication_year = [
                    '0'
                    ], 
                impact_factor_as_of = [
                    '0'
                    ], 
                coden = [
                    '0'
                    ], 
                final_publication_date = [
                    '0'
                    ], 
                music_composer = [
                    None
                    ], 
                type = [
                    '0'
                    ], 
                is_peer_reviewed = [
                    True
                    ], 
                lccn = [
                    '0'
                    ], 
                impact_factor = [
                    1.337
                    ], 
                id = '0', 
                film_version = [
                    None
                    ], 
                author = [
                    None
                    ], 
                runtime = [
                    None
                    ], 
                production_company = [
                    None
                    ], 
                license = [
                    None
                    ], 
                subject_term = [
                    '0'
                    ], 
                issn = [
                    '0'
                    ], 
                producer = [
                    None
                    ], 
                previous_work = [
                    None
                    ], 
                open_access_content = [
                    '0'
                    ], 
                first_publication_year = [
                    '0'
                    ], 
                translator = [
                    None
                    ], 
                alternative_title = [
                    '0'
                    ], 
                description = [
                    '0'
                    ], 
                subsequent_work = [
                    None
                    ], 
                chief_editor = [
                    None
                    ], 
                last_publication_date = [
                    '0'
                    ], 
                lcc = [
                    '0'
                    ], 
                main_character = [
                    None
                    ], 
                literary_genre = [
                    None
                    ], 
                based_on = [
                    None
                    ], 
                first_publisher = [
                    None
                    ], 
                first_publication_date = [
                    '0'
                    ], 
                jstor = [
                    '0'
                    ], 
                release_date = [
                    '0'
                    ], 
                number_of_volumes = [
                    56
                    ], 
                composer = [
                    None
                    ], 
                preface_by = [
                    None
                    ], 
                label = [
                    '0'
                    ], 
                original_language = [
                    None
                    ], 
                original_title = [
                    '0'
                    ], 
                circulation = [
                    56
                    ], 
                oclc = [
                    '0'
                    ], 
                zdb = [
                    '0'
                    ], 
                starring = [
                    None
                    ], 
                completion_date = [
                    '0'
                    ], 
                writer = [
                    None
                    ], 
                magazine = [
                    None
                    ]
            )
        else :
            return AcademicJournal(
        )

    def testAcademicJournal(self):
        """Test AcademicJournal"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
