# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.space_mission_api import SpaceMissionApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSpaceMissionApi(unittest.TestCase):
    """SpaceMissionApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.space_mission_api.SpaceMissionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_spacemissions_get(self):
        """Test case for spacemissions_get

        List all instances of SpaceMission  # noqa: E501
        """
        pass

    def test_spacemissions_id_get(self):
        """Test case for spacemissions_id_get

        Get a single SpaceMission by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
