# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.solar_eclipse_api import SolarEclipseApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSolarEclipseApi(unittest.TestCase):
    """SolarEclipseApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.solar_eclipse_api.SolarEclipseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_solareclipses_get(self):
        """Test case for solareclipses_get

        List all instances of SolarEclipse  # noqa: E501
        """
        pass

    def test_solareclipses_id_get(self):
        """Test case for solareclipses_id_get

        Get a single SolarEclipse by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
