# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.district_water_board_api import DistrictWaterBoardApi  # noqa: E501
from dbpedia.rest import ApiException


class TestDistrictWaterBoardApi(unittest.TestCase):
    """DistrictWaterBoardApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.district_water_board_api.DistrictWaterBoardApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_districtwaterboards_get(self):
        """Test case for districtwaterboards_get

        List all instances of DistrictWaterBoard  # noqa: E501
        """
        pass

    def test_districtwaterboards_id_get(self):
        """Test case for districtwaterboards_id_get

        Get a single DistrictWaterBoard by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
