# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.speedway_league_api import SpeedwayLeagueApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSpeedwayLeagueApi(unittest.TestCase):
    """SpeedwayLeagueApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.speedway_league_api.SpeedwayLeagueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_speedwayleagues_get(self):
        """Test case for speedwayleagues_get

        List all instances of SpeedwayLeague  # noqa: E501
        """
        pass

    def test_speedwayleagues_id_get(self):
        """Test case for speedwayleagues_id_get

        Get a single SpeedwayLeague by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
