# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.play_api import PlayApi  # noqa: E501
from dbpedia.rest import ApiException


class TestPlayApi(unittest.TestCase):
    """PlayApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.play_api.PlayApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_plays_get(self):
        """Test case for plays_get

        List all instances of Play  # noqa: E501
        """
        pass

    def test_plays_id_get(self):
        """Test case for plays_id_get

        Get a single Play by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
