# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.chancellor_api import ChancellorApi  # noqa: E501
from dbpedia.rest import ApiException


class TestChancellorApi(unittest.TestCase):
    """ChancellorApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.chancellor_api.ChancellorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chancellors_get(self):
        """Test case for chancellors_get

        List all instances of Chancellor  # noqa: E501
        """
        pass

    def test_chancellors_id_get(self):
        """Test case for chancellors_id_get

        Get a single Chancellor by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
