# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.historic_place_api import HistoricPlaceApi  # noqa: E501
from dbpedia.rest import ApiException


class TestHistoricPlaceApi(unittest.TestCase):
    """HistoricPlaceApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.historic_place_api.HistoricPlaceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_historicplaces_get(self):
        """Test case for historicplaces_get

        List all instances of HistoricPlace  # noqa: E501
        """
        pass

    def test_historicplaces_id_get(self):
        """Test case for historicplaces_id_get

        Get a single HistoricPlace by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
