# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.synagogue_api import SynagogueApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSynagogueApi(unittest.TestCase):
    """SynagogueApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.synagogue_api.SynagogueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_synagogues_get(self):
        """Test case for synagogues_get

        List all instances of Synagogue  # noqa: E501
        """
        pass

    def test_synagogues_id_get(self):
        """Test case for synagogues_id_get

        Get a single Synagogue by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
