# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.video_game_api import VideoGameApi  # noqa: E501
from dbpedia.rest import ApiException


class TestVideoGameApi(unittest.TestCase):
    """VideoGameApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.video_game_api.VideoGameApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_videogames_get(self):
        """Test case for videogames_get

        List all instances of VideoGame  # noqa: E501
        """
        pass

    def test_videogames_id_get(self):
        """Test case for videogames_id_get

        Get a single VideoGame by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
