# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.controlled_designation_of_origin_wine_api import ControlledDesignationOfOriginWineApi  # noqa: E501
from dbpedia.rest import ApiException


class TestControlledDesignationOfOriginWineApi(unittest.TestCase):
    """ControlledDesignationOfOriginWineApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.controlled_designation_of_origin_wine_api.ControlledDesignationOfOriginWineApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_controlleddesignationoforiginwines_get(self):
        """Test case for controlleddesignationoforiginwines_get

        List all instances of ControlledDesignationOfOriginWine  # noqa: E501
        """
        pass

    def test_controlleddesignationoforiginwines_id_get(self):
        """Test case for controlleddesignationoforiginwines_id_get

        Get a single ControlledDesignationOfOriginWine by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
