# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.bus_company_api import BusCompanyApi  # noqa: E501
from dbpedia.rest import ApiException


class TestBusCompanyApi(unittest.TestCase):
    """BusCompanyApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.bus_company_api.BusCompanyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_buscompanys_get(self):
        """Test case for buscompanys_get

        List all instances of BusCompany  # noqa: E501
        """
        pass

    def test_buscompanys_id_get(self):
        """Test case for buscompanys_id_get

        Get a single BusCompany by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
