# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.marriage_api import MarriageApi  # noqa: E501
from dbpedia.rest import ApiException


class TestMarriageApi(unittest.TestCase):
    """MarriageApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.marriage_api.MarriageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_marriages_get(self):
        """Test case for marriages_get

        List all instances of Marriage  # noqa: E501
        """
        pass

    def test_marriages_id_get(self):
        """Test case for marriages_id_get

        Get a single Marriage by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
