# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.chemical_substance_api import ChemicalSubstanceApi  # noqa: E501
from dbpedia.rest import ApiException


class TestChemicalSubstanceApi(unittest.TestCase):
    """ChemicalSubstanceApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.chemical_substance_api.ChemicalSubstanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chemicalsubstances_get(self):
        """Test case for chemicalsubstances_get

        List all instances of ChemicalSubstance  # noqa: E501
        """
        pass

    def test_chemicalsubstances_id_get(self):
        """Test case for chemicalsubstances_id_get

        Get a single ChemicalSubstance by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
