# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.sports_team_season_api import SportsTeamSeasonApi  # noqa: E501
from dbpedia.rest import ApiException


class TestSportsTeamSeasonApi(unittest.TestCase):
    """SportsTeamSeasonApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.sports_team_season_api.SportsTeamSeasonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sportsteamseasons_get(self):
        """Test case for sportsteamseasons_get

        List all instances of SportsTeamSeason  # noqa: E501
        """
        pass

    def test_sportsteamseasons_id_get(self):
        """Test case for sportsteamseasons_id_get

        Get a single SportsTeamSeason by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
