# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.austrian_settlement_api import AustrianSettlementApi  # noqa: E501
from dbpedia.rest import ApiException


class TestAustrianSettlementApi(unittest.TestCase):
    """AustrianSettlementApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.austrian_settlement_api.AustrianSettlementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_austriansettlements_get(self):
        """Test case for austriansettlements_get

        List all instances of AustrianSettlement  # noqa: E501
        """
        pass

    def test_austriansettlements_id_get(self):
        """Test case for austriansettlements_id_get

        Get a single AustrianSettlement by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
