# coding: utf-8

"""
    DBpedia

    This is the API of the DBpedia Ontology  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dbpedia
from dbpedia.api.nascar_driver_api import NascarDriverApi  # noqa: E501
from dbpedia.rest import ApiException


class TestNascarDriverApi(unittest.TestCase):
    """NascarDriverApi unit test stubs"""

    def setUp(self):
        self.api = dbpedia.api.nascar_driver_api.NascarDriverApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_nascardrivers_get(self):
        """Test case for nascardrivers_get

        List all instances of NascarDriver  # noqa: E501
        """
        pass

    def test_nascardrivers_id_get(self):
        """Test case for nascardrivers_id_get

        Get a single NascarDriver by its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
