__version__      = '0.1.3'
__url__          = 'https://github.com/innodatalabs/ilabs.matchback'
__author__       = 'Mike Kroutikov'
__author_email__ = 'mkroutikov@innodata.com'
__description__  = 'A tool to match inno:dom content back to the source HTML'
__keywords__     = 'innodata inno:dom xml html'