#/usr/bin/env python3

GET_PHOTOS_PATTERN = "https://www.flickr.com/services/rest?method=flickr.people.getPhotos&api_key={}&user_id={}&format=json&page={}&per_page={}"
FIND_USER_BY_NAME_METHOD = "https://www.flickr.com/services/rest?method=flickr.people.findbyusername&api_key={}&username={}&format={}"
GET_PHOTO_COMMENTS = "https://www.flickr.com/services/rest?method=flickr.photos.comments.getList&api_key={}&photo_id={}&format=json"
GET_PHOTO_SIZE_PATTERN = "https://www.flickr.com/services/rest?method=flickr.photos.getSizes&api_key={}&photo_id={}&format=json"
GET_PHOTO_DESCRIPTION = "https://www.flickr.com/services/rest?method=flickr.photos.getInfo&api_key={}&photo_id={}&format=json"
PHOTO_DATA_KEYS = ['id', 'owner', 'secret', 'server', 'farm', 'title', 'ispublic', 'isfriend', 'isfamily']
USER_DATA_PATTERN = r'{"user":{"id":".*","nsid":".*","username":{"_content":".*"}},"stat":"ok"}'
PHOTO_SIZE_URL_PATTERN = r"https://live.staticflickr.com/\d*/.*.jpg"
ALPHANUMERIC = "0123456789abcdefghijklmnopqrstuvwxyz"
CAPITAL_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
ALPHABET = "abcdefghijklmnopqrstuvwxyz"
USER_KEYS = ['id', 'nsid', 'username']
LOCALE_FORMAT = r"^[a-z]*-[A-Z]{2}"
USER_NOT_FOUND = "User not found"
ISO3166_1_FORMAT = r"[A-Z]{2}"
ALPHABET_REGEX = r"[a-zA-Z]*"
ISO639_FORMAT = r"^[a-z]*"
DESCRITION = "description"
USERNAME_KEY = "_content"
USERNAME = "username"
COMMENTS = "comments"
CONTENT = "_content"
COMMENT = "comment"
MESSAGE = 'message'
PHOTOS = "photos"
HEIGHT = "height"
SOURCE = "source"
TITLE = "title"
PAGES = "pages"
PHOTO = "photo"
LABEL = "label"
TOTAL = "total"
WIDTH = "width"
SIZES = "sizes"
JSON = "json"
NSID = "nsid"
SIZE = "size"
USER = "user"
STAT = "stat"
FAIL = "fail"
GET = "GET"
ID = "id"
CONSUMER_KEY = "consumer_key"
CONSUMER_SECRET = "consumer_secret"
FLICKR_KEYS = "flickr_keys"
LOCALE = "locale"