
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-13T22:33:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "08d177f95aa227e9abcfe64d46336b3ea0c5a019",
 "version": "1.9.4.post.dev30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
