
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-29T10:47:13+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c7f351f4cc286c9eb90ebf6dcaf62be81e6b65b",
 "version": "2.0.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
