# Generated by Django 3.0.4 on 2020-05-12 00:55

from django.db import migrations
from edc_export.fix_export_permission import fix_export_permissions


def my_fix_export_permissions(apps, schema_editor):
    fix_export_permissions(apps, schema_editor, "edc_action_item")


class Migration(migrations.Migration):

    dependencies = [
        ("edc_action_item", "0024_auto_20191024_1000"),
    ]

    operations = [migrations.RunPython(my_fix_export_permissions)]
