from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from dbpedia.api.abbey_api import AbbeyApi
from dbpedia.api.academic_journal_api import AcademicJournalApi
from dbpedia.api.activity_api import ActivityApi
from dbpedia.api.actor_api import ActorApi
from dbpedia.api.administrative_region_api import AdministrativeRegionApi
from dbpedia.api.adult_actor_api import AdultActorApi
from dbpedia.api.agent_api import AgentApi
from dbpedia.api.agglomeration_api import AgglomerationApi
from dbpedia.api.aircraft_api import AircraftApi
from dbpedia.api.airline_api import AirlineApi
from dbpedia.api.airport_api import AirportApi
from dbpedia.api.album_api import AlbumApi
from dbpedia.api.algerian_settlement_api import AlgerianSettlementApi
from dbpedia.api.altitude_api import AltitudeApi
from dbpedia.api.amateur_boxer_api import AmateurBoxerApi
from dbpedia.api.ambassador_api import AmbassadorApi
from dbpedia.api.american_football_coach_api import AmericanFootballCoachApi
from dbpedia.api.american_football_league_api import AmericanFootballLeagueApi
from dbpedia.api.american_football_player_api import AmericanFootballPlayerApi
from dbpedia.api.american_football_team_api import AmericanFootballTeamApi
from dbpedia.api.amphibian_api import AmphibianApi
from dbpedia.api.amusement_park_attraction_api import AmusementParkAttractionApi
from dbpedia.api.anatomical_structure_api import AnatomicalStructureApi
from dbpedia.api.animal_api import AnimalApi
from dbpedia.api.animanga_character_api import AnimangaCharacterApi
from dbpedia.api.anime_api import AnimeApi
from dbpedia.api.annotation_api import AnnotationApi
from dbpedia.api.arachnid_api import ArachnidApi
from dbpedia.api.archaea_api import ArchaeaApi
from dbpedia.api.archeologist_api import ArcheologistApi
from dbpedia.api.archipelago_api import ArchipelagoApi
from dbpedia.api.architect_api import ArchitectApi
from dbpedia.api.architectural_structure_api import ArchitecturalStructureApi
from dbpedia.api.archive_api import ArchiveApi
from dbpedia.api.area_api import AreaApi
from dbpedia.api.arena_api import ArenaApi
from dbpedia.api.aristocrat_api import AristocratApi
from dbpedia.api.artery_api import ArteryApi
from dbpedia.api.artificial_satellite_api import ArtificialSatelliteApi
from dbpedia.api.artist_api import ArtistApi
from dbpedia.api.artist_discography_api import ArtistDiscographyApi
from dbpedia.api.artwork_api import ArtworkApi
from dbpedia.api.asteroid_api import AsteroidApi
from dbpedia.api.astronaut_api import AstronautApi
from dbpedia.api.athlete_api import AthleteApi
from dbpedia.api.athletics_api import AthleticsApi
from dbpedia.api.athletics_player_api import AthleticsPlayerApi
from dbpedia.api.atoll_api import AtollApi
from dbpedia.api.australian_football_league_api import AustralianFootballLeagueApi
from dbpedia.api.australian_football_team_api import AustralianFootballTeamApi
from dbpedia.api.australian_rules_football_player_api import AustralianRulesFootballPlayerApi
from dbpedia.api.austrian_administrative_region_api import AustrianAdministrativeRegionApi
from dbpedia.api.austrian_settlement_api import AustrianSettlementApi
from dbpedia.api.auto_racing_league_api import AutoRacingLeagueApi
from dbpedia.api.automobile_api import AutomobileApi
from dbpedia.api.automobile_engine_api import AutomobileEngineApi
from dbpedia.api.award_api import AwardApi
from dbpedia.api.back_scene_api import BackSceneApi
from dbpedia.api.bacteria_api import BacteriaApi
from dbpedia.api.badminton_player_api import BadmintonPlayerApi
from dbpedia.api.band_api import BandApi
from dbpedia.api.baronet_api import BaronetApi
from dbpedia.api.baseball_league_api import BaseballLeagueApi
from dbpedia.api.baseball_player_api import BaseballPlayerApi
from dbpedia.api.baseball_season_api import BaseballSeasonApi
from dbpedia.api.baseball_team_api import BaseballTeamApi
from dbpedia.api.basketball_league_api import BasketballLeagueApi
from dbpedia.api.basketball_player_api import BasketballPlayerApi
from dbpedia.api.basketball_team_api import BasketballTeamApi
from dbpedia.api.beach_volleyball_player_api import BeachVolleyballPlayerApi
from dbpedia.api.beauty_queen_api import BeautyQueenApi
from dbpedia.api.beer_api import BeerApi
from dbpedia.api.belgium_settlement_api import BelgiumSettlementApi
from dbpedia.api.beverage_api import BeverageApi
from dbpedia.api.biological_database_api import BiologicalDatabaseApi
from dbpedia.api.biomolecule_api import BiomoleculeApi
from dbpedia.api.bird_api import BirdApi
from dbpedia.api.birth_api import BirthApi
from dbpedia.api.blazon_api import BlazonApi
from dbpedia.api.board_game_api import BoardGameApi
from dbpedia.api.body_of_water_api import BodyOfWaterApi
from dbpedia.api.bodybuilder_api import BodybuilderApi
from dbpedia.api.bone_api import BoneApi
from dbpedia.api.book_api import BookApi
from dbpedia.api.bowling_league_api import BowlingLeagueApi
from dbpedia.api.boxer_api import BoxerApi
from dbpedia.api.boxing_api import BoxingApi
from dbpedia.api.boxing_category_api import BoxingCategoryApi
from dbpedia.api.boxing_league_api import BoxingLeagueApi
from dbpedia.api.boxing_style_api import BoxingStyleApi
from dbpedia.api.brain_api import BrainApi
from dbpedia.api.brewery_api import BreweryApi
from dbpedia.api.bridge_api import BridgeApi
from dbpedia.api.british_royalty_api import BritishRoyaltyApi
from dbpedia.api.broadcast_network_api import BroadcastNetworkApi
from dbpedia.api.broadcaster_api import BroadcasterApi
from dbpedia.api.brown_dwarf_api import BrownDwarfApi
from dbpedia.api.building_api import BuildingApi
from dbpedia.api.bullfighter_api import BullfighterApi
from dbpedia.api.bus_company_api import BusCompanyApi
from dbpedia.api.business_person_api import BusinessPersonApi
from dbpedia.api.camera_api import CameraApi
from dbpedia.api.canadian_football_league_api import CanadianFootballLeagueApi
from dbpedia.api.canadian_football_player_api import CanadianFootballPlayerApi
from dbpedia.api.canadian_football_team_api import CanadianFootballTeamApi
from dbpedia.api.canal_api import CanalApi
from dbpedia.api.canoeist_api import CanoeistApi
from dbpedia.api.capital_api import CapitalApi
from dbpedia.api.capital_of_region_api import CapitalOfRegionApi
from dbpedia.api.cardinal_api import CardinalApi
from dbpedia.api.career_station_api import CareerStationApi
from dbpedia.api.cartoon_api import CartoonApi
from dbpedia.api.case_api import CaseApi
from dbpedia.api.casino_api import CasinoApi
from dbpedia.api.castle_api import CastleApi
from dbpedia.api.cave_api import CaveApi
from dbpedia.api.celebrity_api import CelebrityApi
from dbpedia.api.celestial_body_api import CelestialBodyApi
from dbpedia.api.cemetery_api import CemeteryApi
from dbpedia.api.chancellor_api import ChancellorApi
from dbpedia.api.charts_placements_api import ChartsPlacementsApi
from dbpedia.api.cheese_api import CheeseApi
from dbpedia.api.chef_api import ChefApi
from dbpedia.api.chemical_compound_api import ChemicalCompoundApi
from dbpedia.api.chemical_element_api import ChemicalElementApi
from dbpedia.api.chemical_substance_api import ChemicalSubstanceApi
from dbpedia.api.chess_player_api import ChessPlayerApi
from dbpedia.api.christian_bishop_api import ChristianBishopApi
from dbpedia.api.christian_doctrine_api import ChristianDoctrineApi
from dbpedia.api.christian_patriarch_api import ChristianPatriarchApi
from dbpedia.api.church_api import ChurchApi
from dbpedia.api.city_api import CityApi
from dbpedia.api.city_district_api import CityDistrictApi
from dbpedia.api.classical_music_artist_api import ClassicalMusicArtistApi
from dbpedia.api.classical_music_composition_api import ClassicalMusicCompositionApi
from dbpedia.api.cleric_api import ClericApi
from dbpedia.api.clerical_administrative_region_api import ClericalAdministrativeRegionApi
from dbpedia.api.clerical_order_api import ClericalOrderApi
from dbpedia.api.club_moss_api import ClubMossApi
from dbpedia.api.coach_api import CoachApi
from dbpedia.api.collection_of_valuables_api import CollectionOfValuablesApi
from dbpedia.api.college_api import CollegeApi
from dbpedia.api.college_coach_api import CollegeCoachApi
from dbpedia.api.colour_api import ColourApi
from dbpedia.api.comedian_api import ComedianApi
from dbpedia.api.comedy_group_api import ComedyGroupApi
from dbpedia.api.comic_api import ComicApi
from dbpedia.api.comic_strip_api import ComicStripApi
from dbpedia.api.comics_api import ComicsApi
from dbpedia.api.comics_character_api import ComicsCharacterApi
from dbpedia.api.comics_creator_api import ComicsCreatorApi
from dbpedia.api.community_api import CommunityApi
from dbpedia.api.company_api import CompanyApi
from dbpedia.api.competition_api import CompetitionApi
from dbpedia.api.congressman_api import CongressmanApi
from dbpedia.api.conifer_api import ConiferApi
from dbpedia.api.constellation_api import ConstellationApi
from dbpedia.api.contest_api import ContestApi
from dbpedia.api.continent_api import ContinentApi
from dbpedia.api.controlled_designation_of_origin_wine_api import ControlledDesignationOfOriginWineApi
from dbpedia.api.convention_api import ConventionApi
from dbpedia.api.country_api import CountryApi
from dbpedia.api.country_seat_api import CountrySeatApi
from dbpedia.api.crater_api import CraterApi
from dbpedia.api.cricket_ground_api import CricketGroundApi
from dbpedia.api.cricket_league_api import CricketLeagueApi
from dbpedia.api.cricket_team_api import CricketTeamApi
from dbpedia.api.cricketer_api import CricketerApi
from dbpedia.api.criminal_api import CriminalApi
from dbpedia.api.crustacean_api import CrustaceanApi
from dbpedia.api.cultivated_variety_api import CultivatedVarietyApi
from dbpedia.api.curler_api import CurlerApi
from dbpedia.api.curling_league_api import CurlingLeagueApi
from dbpedia.api.currency_api import CurrencyApi
from dbpedia.api.cycad_api import CycadApi
from dbpedia.api.cycling_competition_api import CyclingCompetitionApi
from dbpedia.api.cycling_league_api import CyclingLeagueApi
from dbpedia.api.cycling_race_api import CyclingRaceApi
from dbpedia.api.cycling_team_api import CyclingTeamApi
from dbpedia.api.cyclist_api import CyclistApi
from dbpedia.api.dam_api import DamApi
from dbpedia.api.dancer_api import DancerApi
from dbpedia.api.darts_player_api import DartsPlayerApi
from dbpedia.api.database_api import DatabaseApi
from dbpedia.api.deanery_api import DeaneryApi
from dbpedia.api.death_api import DeathApi
from dbpedia.api.decoration_api import DecorationApi
from dbpedia.api.deity_api import DeityApi
from dbpedia.api.demographics_api import DemographicsApi
from dbpedia.api.department_api import DepartmentApi
from dbpedia.api.depth_api import DepthApi
from dbpedia.api.deputy_api import DeputyApi
from dbpedia.api.desert_api import DesertApi
from dbpedia.api.device_api import DeviceApi
from dbpedia.api.digital_camera_api import DigitalCameraApi
from dbpedia.api.diocese_api import DioceseApi
from dbpedia.api.diploma_api import DiplomaApi
from dbpedia.api.disease_api import DiseaseApi
from dbpedia.api.disney_character_api import DisneyCharacterApi
from dbpedia.api.district_api import DistrictApi
from dbpedia.api.district_water_board_api import DistrictWaterBoardApi
from dbpedia.api.divorce_api import DivorceApi
from dbpedia.api.document_api import DocumentApi
from dbpedia.api.document_type_api import DocumentTypeApi
from dbpedia.api.dog_api import DogApi
from dbpedia.api.drama_api import DramaApi
from dbpedia.api.drug_api import DrugApi
from dbpedia.api.economist_api import EconomistApi
from dbpedia.api.educational_institution_api import EducationalInstitutionApi
from dbpedia.api.egyptologist_api import EgyptologistApi
from dbpedia.api.election_api import ElectionApi
from dbpedia.api.election_diagram_api import ElectionDiagramApi
from dbpedia.api.embryology_api import EmbryologyApi
from dbpedia.api.employer_api import EmployerApi
from dbpedia.api.engineer_api import EngineerApi
from dbpedia.api.entomologist_api import EntomologistApi
from dbpedia.api.enzyme_api import EnzymeApi
from dbpedia.api.ethnic_group_api import EthnicGroupApi
from dbpedia.api.eukaryote_api import EukaryoteApi
from dbpedia.api.eurovision_song_contest_entry_api import EurovisionSongContestEntryApi
from dbpedia.api.event_api import EventApi
from dbpedia.api.factory_api import FactoryApi
from dbpedia.api.family_api import FamilyApi
from dbpedia.api.farmer_api import FarmerApi
from dbpedia.api.fashion_api import FashionApi
from dbpedia.api.fashion_designer_api import FashionDesignerApi
from dbpedia.api.fencer_api import FencerApi
from dbpedia.api.fern_api import FernApi
from dbpedia.api.fictional_character_api import FictionalCharacterApi
from dbpedia.api.field_hockey_league_api import FieldHockeyLeagueApi
from dbpedia.api.figure_skater_api import FigureSkaterApi
from dbpedia.api.film_api import FilmApi
from dbpedia.api.film_festival_api import FilmFestivalApi
from dbpedia.api.fish_api import FishApi
from dbpedia.api.flag_api import FlagApi
from dbpedia.api.flowering_plant_api import FloweringPlantApi
from dbpedia.api.food_api import FoodApi
from dbpedia.api.football_league_season_api import FootballLeagueSeasonApi
from dbpedia.api.football_match_api import FootballMatchApi
from dbpedia.api.former_municipality_api import FormerMunicipalityApi
from dbpedia.api.formula_one_racer_api import FormulaOneRacerApi
from dbpedia.api.formula_one_racing_api import FormulaOneRacingApi
from dbpedia.api.formula_one_team_api import FormulaOneTeamApi
from dbpedia.api.fungus_api import FungusApi
from dbpedia.api.gaelic_games_player_api import GaelicGamesPlayerApi
from dbpedia.api.galaxy_api import GalaxyApi
from dbpedia.api.game_api import GameApi
from dbpedia.api.garden_api import GardenApi
from dbpedia.api.gate_api import GateApi
from dbpedia.api.gated_community_api import GatedCommunityApi
from dbpedia.api.gene_api import GeneApi
from dbpedia.api.gene_location_api import GeneLocationApi
from dbpedia.api.genre_api import GenreApi
from dbpedia.api.geological_period_api import GeologicalPeriodApi
from dbpedia.api.geopolitical_organisation_api import GeopoliticalOrganisationApi
from dbpedia.api.german_settlement_api import GermanSettlementApi
from dbpedia.api.ginkgo_api import GinkgoApi
from dbpedia.api.given_name_api import GivenNameApi
from dbpedia.api.glacier_api import GlacierApi
from dbpedia.api.globularswarm_api import GlobularswarmApi
from dbpedia.api.gnetophytes_api import GnetophytesApi
from dbpedia.api.golf_course_api import GolfCourseApi
from dbpedia.api.golf_league_api import GolfLeagueApi
from dbpedia.api.golf_player_api import GolfPlayerApi
from dbpedia.api.golf_tournament_api import GolfTournamentApi
from dbpedia.api.government_agency_api import GovernmentAgencyApi
from dbpedia.api.government_type_api import GovernmentTypeApi
from dbpedia.api.governmental_administrative_region_api import GovernmentalAdministrativeRegionApi
from dbpedia.api.governor_api import GovernorApi
from dbpedia.api.grand_prix_api import GrandPrixApi
from dbpedia.api.grape_api import GrapeApi
from dbpedia.api.grave_monument_api import GraveMonumentApi
from dbpedia.api.green_alga_api import GreenAlgaApi
from dbpedia.api.gridiron_football_player_api import GridironFootballPlayerApi
from dbpedia.api.gross_domestic_product_api import GrossDomesticProductApi
from dbpedia.api.gross_domestic_product_per_capita_api import GrossDomesticProductPerCapitaApi
from dbpedia.api.group_api import GroupApi
from dbpedia.api.guitar_api import GuitarApi
from dbpedia.api.guitarist_api import GuitaristApi
from dbpedia.api.gymnast_api import GymnastApi
from dbpedia.api.handball_league_api import HandballLeagueApi
from dbpedia.api.handball_player_api import HandballPlayerApi
from dbpedia.api.handball_team_api import HandballTeamApi
from dbpedia.api.historian_api import HistorianApi
from dbpedia.api.historic_building_api import HistoricBuildingApi
from dbpedia.api.historic_place_api import HistoricPlaceApi
from dbpedia.api.historical_country_api import HistoricalCountryApi
from dbpedia.api.historical_district_api import HistoricalDistrictApi
from dbpedia.api.historical_period_api import HistoricalPeriodApi
from dbpedia.api.historical_province_api import HistoricalProvinceApi
from dbpedia.api.historical_region_api import HistoricalRegionApi
from dbpedia.api.historical_settlement_api import HistoricalSettlementApi
from dbpedia.api.hockey_team_api import HockeyTeamApi
from dbpedia.api.holiday_api import HolidayApi
from dbpedia.api.hollywood_cartoon_api import HollywoodCartoonApi
from dbpedia.api.horse_race_api import HorseRaceApi
from dbpedia.api.horse_rider_api import HorseRiderApi
from dbpedia.api.horse_riding_api import HorseRidingApi
from dbpedia.api.horse_trainer_api import HorseTrainerApi
from dbpedia.api.hospital_api import HospitalApi
from dbpedia.api.host_api import HostApi
from dbpedia.api.hot_spring_api import HotSpringApi
from dbpedia.api.hotel_api import HotelApi
from dbpedia.api.human_development_index_api import HumanDevelopmentIndexApi
from dbpedia.api.human_gene_api import HumanGeneApi
from dbpedia.api.human_gene_location_api import HumanGeneLocationApi
from dbpedia.api.humorist_api import HumoristApi
from dbpedia.api.hungary_settlement_api import HungarySettlementApi
from dbpedia.api.ice_hockey_league_api import IceHockeyLeagueApi
from dbpedia.api.ice_hockey_player_api import IceHockeyPlayerApi
from dbpedia.api.ideology_api import IdeologyApi
from dbpedia.api.image_api import ImageApi
from dbpedia.api.imdb_api import ImdbApi
from dbpedia.api.information_appliance_api import InformationApplianceApi
from dbpedia.api.infrastructure_api import InfrastructureApi
from dbpedia.api.inline_hockey_league_api import InlineHockeyLeagueApi
from dbpedia.api.insect_api import InsectApi
from dbpedia.api.installment_api import InstallmentApi
from dbpedia.api.instrument_api import InstrumentApi
from dbpedia.api.instrumentalist_api import InstrumentalistApi
from dbpedia.api.intercommunality_api import IntercommunalityApi
from dbpedia.api.island_api import IslandApi
from dbpedia.api.jockey_api import JockeyApi
from dbpedia.api.journalist_api import JournalistApi
from dbpedia.api.judge_api import JudgeApi
from dbpedia.api.lacrosse_league_api import LacrosseLeagueApi
from dbpedia.api.lacrosse_player_api import LacrossePlayerApi
from dbpedia.api.lake_api import LakeApi
from dbpedia.api.language_api import LanguageApi
from dbpedia.api.launch_pad_api import LaunchPadApi
from dbpedia.api.law_firm_api import LawFirmApi
from dbpedia.api.lawyer_api import LawyerApi
from dbpedia.api.lebanon_settlement_api import LebanonSettlementApi
from dbpedia.api.legal_case_api import LegalCaseApi
from dbpedia.api.legislature_api import LegislatureApi
from dbpedia.api.letter_api import LetterApi
from dbpedia.api.library_api import LibraryApi
from dbpedia.api.liechtenstein_settlement_api import LiechtensteinSettlementApi
from dbpedia.api.lieutenant_api import LieutenantApi
from dbpedia.api.life_cycle_event_api import LifeCycleEventApi
from dbpedia.api.ligament_api import LigamentApi
from dbpedia.api.light_novel_api import LightNovelApi
from dbpedia.api.lighthouse_api import LighthouseApi
from dbpedia.api.line_of_fashion_api import LineOfFashionApi
from dbpedia.api.linguist_api import LinguistApi
from dbpedia.api.list_api import ListApi
from dbpedia.api.listen_api import ListenApi
from dbpedia.api.locality_api import LocalityApi
from dbpedia.api.lock_api import LockApi
from dbpedia.api.locomotive_api import LocomotiveApi
from dbpedia.api.lunar_crater_api import LunarCraterApi
from dbpedia.api.lymph_api import LymphApi
from dbpedia.api.magazine_api import MagazineApi
from dbpedia.api.mammal_api import MammalApi
from dbpedia.api.manga_api import MangaApi
from dbpedia.api.manhua_api import ManhuaApi
from dbpedia.api.manhwa_api import ManhwaApi
from dbpedia.api.marriage_api import MarriageApi
from dbpedia.api.martial_artist_api import MartialArtistApi
from dbpedia.api.mayor_api import MayorApi
from dbpedia.api.mean_of_transportation_api import MeanOfTransportationApi
from dbpedia.api.media_api import MediaApi
from dbpedia.api.medician_api import MedicianApi
from dbpedia.api.meeting_api import MeetingApi
from dbpedia.api.member_of_parliament_api import MemberOfParliamentApi
from dbpedia.api.memorial_api import MemorialApi
from dbpedia.api.metro_station_api import MetroStationApi
from dbpedia.api.micro_region_api import MicroRegionApi
from dbpedia.api.military_conflict_api import MilitaryConflictApi
from dbpedia.api.military_person_api import MilitaryPersonApi
from dbpedia.api.military_structure_api import MilitaryStructureApi
from dbpedia.api.military_unit_api import MilitaryUnitApi
from dbpedia.api.mill_api import MillApi
from dbpedia.api.mineral_api import MineralApi
from dbpedia.api.mixed_martial_arts_event_api import MixedMartialArtsEventApi
from dbpedia.api.mixed_martial_arts_league_api import MixedMartialArtsLeagueApi
from dbpedia.api.model_api import ModelApi
from dbpedia.api.mollusca_api import MolluscaApi
from dbpedia.api.monarch_api import MonarchApi
from dbpedia.api.monastery_api import MonasteryApi
from dbpedia.api.monastry_api import MonastryApi
from dbpedia.api.monument_api import MonumentApi
from dbpedia.api.mosque_api import MosqueApi
from dbpedia.api.moss_api import MossApi
from dbpedia.api.motocycle_racer_api import MotocycleRacerApi
from dbpedia.api.motorcycle_api import MotorcycleApi
from dbpedia.api.motorcycle_racing_league_api import MotorcycleRacingLeagueApi
from dbpedia.api.motorcycle_rider_api import MotorcycleRiderApi
from dbpedia.api.motorsport_racer_api import MotorsportRacerApi
from dbpedia.api.motorsport_season_api import MotorsportSeasonApi
from dbpedia.api.mountain_api import MountainApi
from dbpedia.api.mountain_pass_api import MountainPassApi
from dbpedia.api.mountain_range_api import MountainRangeApi
from dbpedia.api.mouse_gene_api import MouseGeneApi
from dbpedia.api.mouse_gene_location_api import MouseGeneLocationApi
from dbpedia.api.movie_director_api import MovieDirectorApi
from dbpedia.api.movie_genre_api import MovieGenreApi
from dbpedia.api.moving_image_api import MovingImageApi
from dbpedia.api.multi_volume_publication_api import MultiVolumePublicationApi
from dbpedia.api.municipality_api import MunicipalityApi
from dbpedia.api.murderer_api import MurdererApi
from dbpedia.api.muscle_api import MuscleApi
from dbpedia.api.museum_api import MuseumApi
from dbpedia.api.music_composer_api import MusicComposerApi
from dbpedia.api.music_director_api import MusicDirectorApi
from dbpedia.api.music_festival_api import MusicFestivalApi
from dbpedia.api.music_genre_api import MusicGenreApi
from dbpedia.api.musical_api import MusicalApi
from dbpedia.api.musical_artist_api import MusicalArtistApi
from dbpedia.api.musical_work_api import MusicalWorkApi
from dbpedia.api.mythological_figure_api import MythologicalFigureApi
from dbpedia.api.ncaa_team_season_api import NCAATeamSeasonApi
from dbpedia.api.name_api import NameApi
from dbpedia.api.naruto_character_api import NarutoCharacterApi
from dbpedia.api.nascar_driver_api import NascarDriverApi
from dbpedia.api.national_anthem_api import NationalAnthemApi
from dbpedia.api.national_collegiate_athletic_association_athlete_api import NationalCollegiateAthleticAssociationAthleteApi
from dbpedia.api.national_football_league_event_api import NationalFootballLeagueEventApi
from dbpedia.api.national_football_league_season_api import NationalFootballLeagueSeasonApi
from dbpedia.api.national_soccer_club_api import NationalSoccerClubApi
from dbpedia.api.natural_event_api import NaturalEventApi
from dbpedia.api.natural_place_api import NaturalPlaceApi
from dbpedia.api.natural_region_api import NaturalRegionApi
from dbpedia.api.nerve_api import NerveApi
from dbpedia.api.netball_player_api import NetballPlayerApi
from dbpedia.api.newspaper_api import NewspaperApi
from dbpedia.api.nobel_prize_api import NobelPrizeApi
from dbpedia.api.noble_api import NobleApi
from dbpedia.api.noble_family_api import NobleFamilyApi
from dbpedia.api.non_profit_organisation_api import NonProfitOrganisationApi
from dbpedia.api.norway_settlement_api import NorwaySettlementApi
from dbpedia.api.noteworthy_part_of_building_api import NoteworthyPartOfBuildingApi
from dbpedia.api.novel_api import NovelApi
from dbpedia.api.nuclear_power_station_api import NuclearPowerStationApi
from dbpedia.api.ocean_api import OceanApi
from dbpedia.api.office_holder_api import OfficeHolderApi
from dbpedia.api.old_territory_api import OldTerritoryApi
from dbpedia.api.olympic_event_api import OlympicEventApi
from dbpedia.api.olympic_result_api import OlympicResultApi
from dbpedia.api.olympics_api import OlympicsApi
from dbpedia.api.opera_api import OperaApi
from dbpedia.api.organ_api import OrganApi
from dbpedia.api.organisation_api import OrganisationApi
from dbpedia.api.organisation_member_api import OrganisationMemberApi
from dbpedia.api.overseas_department_api import OverseasDepartmentApi
from dbpedia.api.paintball_league_api import PaintballLeagueApi
from dbpedia.api.painter_api import PainterApi
from dbpedia.api.painting_api import PaintingApi
from dbpedia.api.parish_api import ParishApi
from dbpedia.api.park_api import ParkApi
from dbpedia.api.parliament_api import ParliamentApi
from dbpedia.api.penalty_shoot_out_api import PenaltyShootOutApi
from dbpedia.api.period_of_artistic_style_api import PeriodOfArtisticStyleApi
from dbpedia.api.periodical_literature_api import PeriodicalLiteratureApi
from dbpedia.api.person_api import PersonApi
from dbpedia.api.person_function_api import PersonFunctionApi
from dbpedia.api.personal_event_api import PersonalEventApi
from dbpedia.api.philosopher_api import PhilosopherApi
from dbpedia.api.photographer_api import PhotographerApi
from dbpedia.api.place_api import PlaceApi
from dbpedia.api.planet_api import PlanetApi
from dbpedia.api.plant_api import PlantApi
from dbpedia.api.play_api import PlayApi
from dbpedia.api.play_wright_api import PlayWrightApi
from dbpedia.api.playboy_playmate_api import PlayboyPlaymateApi
from dbpedia.api.poem_api import PoemApi
from dbpedia.api.poet_api import PoetApi
from dbpedia.api.poker_player_api import PokerPlayerApi
from dbpedia.api.polish_king_api import PolishKingApi
from dbpedia.api.political_function_api import PoliticalFunctionApi
from dbpedia.api.political_party_api import PoliticalPartyApi
from dbpedia.api.politician_api import PoliticianApi
from dbpedia.api.politician_spouse_api import PoliticianSpouseApi
from dbpedia.api.polo_league_api import PoloLeagueApi
from dbpedia.api.polyhedron_api import PolyhedronApi
from dbpedia.api.pope_api import PopeApi
from dbpedia.api.populated_place_api import PopulatedPlaceApi
from dbpedia.api.population_api import PopulationApi
from dbpedia.api.port_api import PortApi
from dbpedia.api.power_station_api import PowerStationApi
from dbpedia.api.prefecture_api import PrefectureApi
from dbpedia.api.prehistorical_period_api import PrehistoricalPeriodApi
from dbpedia.api.presenter_api import PresenterApi
from dbpedia.api.president_api import PresidentApi
from dbpedia.api.priest_api import PriestApi
from dbpedia.api.prime_minister_api import PrimeMinisterApi
from dbpedia.api.prison_api import PrisonApi
from dbpedia.api.producer_api import ProducerApi
from dbpedia.api.profession_api import ProfessionApi
from dbpedia.api.professor_api import ProfessorApi
from dbpedia.api.programming_language_api import ProgrammingLanguageApi
from dbpedia.api.project_api import ProjectApi
from dbpedia.api.protected_area_api import ProtectedAreaApi
from dbpedia.api.protein_api import ProteinApi
from dbpedia.api.protohistorical_period_api import ProtohistoricalPeriodApi
from dbpedia.api.province_api import ProvinceApi
from dbpedia.api.psychologist_api import PsychologistApi
from dbpedia.api.public_service_api import PublicServiceApi
from dbpedia.api.public_service_input_api import PublicServiceInputApi
from dbpedia.api.public_service_output_api import PublicServiceOutputApi
from dbpedia.api.public_transit_system_api import PublicTransitSystemApi
from dbpedia.api.publisher_api import PublisherApi
from dbpedia.api.pyramid_api import PyramidApi
from dbpedia.api.race_api import RaceApi
from dbpedia.api.race_horse_api import RaceHorseApi
from dbpedia.api.race_track_api import RaceTrackApi
from dbpedia.api.racecourse_api import RacecourseApi
from dbpedia.api.racing_driver_api import RacingDriverApi
from dbpedia.api.radio_controlled_racing_league_api import RadioControlledRacingLeagueApi
from dbpedia.api.radio_host_api import RadioHostApi
from dbpedia.api.radio_program_api import RadioProgramApi
from dbpedia.api.radio_station_api import RadioStationApi
from dbpedia.api.railway_line_api import RailwayLineApi
from dbpedia.api.railway_station_api import RailwayStationApi
from dbpedia.api.railway_tunnel_api import RailwayTunnelApi
from dbpedia.api.rally_driver_api import RallyDriverApi
from dbpedia.api.record_label_api import RecordLabelApi
from dbpedia.api.record_office_api import RecordOfficeApi
from dbpedia.api.referee_api import RefereeApi
from dbpedia.api.reference_api import ReferenceApi
from dbpedia.api.regency_api import RegencyApi
from dbpedia.api.region_api import RegionApi
from dbpedia.api.religious_api import ReligiousApi
from dbpedia.api.religious_building_api import ReligiousBuildingApi
from dbpedia.api.reptile_api import ReptileApi
from dbpedia.api.research_project_api import ResearchProjectApi
from dbpedia.api.restaurant_api import RestaurantApi
from dbpedia.api.resume_api import ResumeApi
from dbpedia.api.river_api import RiverApi
from dbpedia.api.road_api import RoadApi
from dbpedia.api.road_junction_api import RoadJunctionApi
from dbpedia.api.road_tunnel_api import RoadTunnelApi
from dbpedia.api.rocket_api import RocketApi
from dbpedia.api.roller_coaster_api import RollerCoasterApi
from dbpedia.api.roman_emperor_api import RomanEmperorApi
from dbpedia.api.romania_settlement_api import RomaniaSettlementApi
from dbpedia.api.route_of_transportation_api import RouteOfTransportationApi
from dbpedia.api.rower_api import RowerApi
from dbpedia.api.royalty_api import RoyaltyApi
from dbpedia.api.rugby_club_api import RugbyClubApi
from dbpedia.api.rugby_league_api import RugbyLeagueApi
from dbpedia.api.rugby_player_api import RugbyPlayerApi
from dbpedia.api.saint_api import SaintApi
from dbpedia.api.sales_api import SalesApi
from dbpedia.api.samba_school_api import SambaSchoolApi
from dbpedia.api.satellite_api import SatelliteApi
from dbpedia.api.school_api import SchoolApi
from dbpedia.api.scientist_api import ScientistApi
from dbpedia.api.screen_writer_api import ScreenWriterApi
from dbpedia.api.sculptor_api import SculptorApi
from dbpedia.api.sculpture_api import SculptureApi
from dbpedia.api.sea_api import SeaApi
from dbpedia.api.senator_api import SenatorApi
from dbpedia.api.serial_killer_api import SerialKillerApi
from dbpedia.api.settlement_api import SettlementApi
from dbpedia.api.ship_api import ShipApi
from dbpedia.api.shopping_mall_api import ShoppingMallApi
from dbpedia.api.shrine_api import ShrineApi
from dbpedia.api.singer_api import SingerApi
from dbpedia.api.single_api import SingleApi
from dbpedia.api.site_of_special_scientific_interest_api import SiteOfSpecialScientificInterestApi
from dbpedia.api.skater_api import SkaterApi
from dbpedia.api.ski_area_api import SkiAreaApi
from dbpedia.api.ski_resort_api import SkiResortApi
from dbpedia.api.skier_api import SkierApi
from dbpedia.api.skyscraper_api import SkyscraperApi
from dbpedia.api.snooker_champ_api import SnookerChampApi
from dbpedia.api.snooker_player_api import SnookerPlayerApi
from dbpedia.api.snooker_world_ranking_api import SnookerWorldRankingApi
from dbpedia.api.soap_character_api import SoapCharacterApi
from dbpedia.api.soccer_club_api import SoccerClubApi
from dbpedia.api.soccer_club_season_api import SoccerClubSeasonApi
from dbpedia.api.soccer_league_api import SoccerLeagueApi
from dbpedia.api.soccer_league_season_api import SoccerLeagueSeasonApi
from dbpedia.api.soccer_manager_api import SoccerManagerApi
from dbpedia.api.soccer_player_api import SoccerPlayerApi
from dbpedia.api.soccer_tournament_api import SoccerTournamentApi
from dbpedia.api.societal_event_api import SocietalEventApi
from dbpedia.api.softball_league_api import SoftballLeagueApi
from dbpedia.api.software_api import SoftwareApi
from dbpedia.api.solar_eclipse_api import SolarEclipseApi
from dbpedia.api.song_api import SongApi
from dbpedia.api.song_writer_api import SongWriterApi
from dbpedia.api.sound_api import SoundApi
from dbpedia.api.space_mission_api import SpaceMissionApi
from dbpedia.api.space_shuttle_api import SpaceShuttleApi
from dbpedia.api.space_station_api import SpaceStationApi
from dbpedia.api.spacecraft_api import SpacecraftApi
from dbpedia.api.species_api import SpeciesApi
from dbpedia.api.speedway_league_api import SpeedwayLeagueApi
from dbpedia.api.speedway_rider_api import SpeedwayRiderApi
from dbpedia.api.speedway_team_api import SpeedwayTeamApi
from dbpedia.api.sport_api import SportApi
from dbpedia.api.sport_competition_result_api import SportCompetitionResultApi
from dbpedia.api.sport_facility_api import SportFacilityApi
from dbpedia.api.sports_event_api import SportsEventApi
from dbpedia.api.sports_league_api import SportsLeagueApi
from dbpedia.api.sports_manager_api import SportsManagerApi
from dbpedia.api.sports_season_api import SportsSeasonApi
from dbpedia.api.sports_team_api import SportsTeamApi
from dbpedia.api.sports_team_member_api import SportsTeamMemberApi
from dbpedia.api.sports_team_season_api import SportsTeamSeasonApi
from dbpedia.api.square_api import SquareApi
from dbpedia.api.squash_player_api import SquashPlayerApi
from dbpedia.api.stadium_api import StadiumApi
from dbpedia.api.star_api import StarApi
from dbpedia.api.state_api import StateApi
from dbpedia.api.stated_resolution_api import StatedResolutionApi
from dbpedia.api.station_api import StationApi
from dbpedia.api.statistic_api import StatisticApi
from dbpedia.api.still_image_api import StillImageApi
from dbpedia.api.stream_api import StreamApi
from dbpedia.api.street_api import StreetApi
from dbpedia.api.sub_municipality_api import SubMunicipalityApi
from dbpedia.api.sumo_wrestler_api import SumoWrestlerApi
from dbpedia.api.supreme_court_of_the_united_states_case_api import SupremeCourtOfTheUnitedStatesCaseApi
from dbpedia.api.surfer_api import SurferApi
from dbpedia.api.surname_api import SurnameApi
from dbpedia.api.swarm_api import SwarmApi
from dbpedia.api.swimmer_api import SwimmerApi
from dbpedia.api.switzerland_settlement_api import SwitzerlandSettlementApi
from dbpedia.api.synagogue_api import SynagogueApi
from dbpedia.api.system_of_law_api import SystemOfLawApi
from dbpedia.api.table_tennis_player_api import TableTennisPlayerApi
from dbpedia.api.tax_api import TaxApi
from dbpedia.api.taxon_api import TaxonApi
from dbpedia.api.team_member_api import TeamMemberApi
from dbpedia.api.television_director_api import TelevisionDirectorApi
from dbpedia.api.television_episode_api import TelevisionEpisodeApi
from dbpedia.api.television_host_api import TelevisionHostApi
from dbpedia.api.television_personality_api import TelevisionPersonalityApi
from dbpedia.api.television_season_api import TelevisionSeasonApi
from dbpedia.api.television_show_api import TelevisionShowApi
from dbpedia.api.television_station_api import TelevisionStationApi
from dbpedia.api.temple_api import TempleApi
from dbpedia.api.tennis_league_api import TennisLeagueApi
from dbpedia.api.tennis_player_api import TennisPlayerApi
from dbpedia.api.tennis_tournament_api import TennisTournamentApi
from dbpedia.api.term_of_office_api import TermOfOfficeApi
from dbpedia.api.territory_api import TerritoryApi
from dbpedia.api.theatre_api import TheatreApi
from dbpedia.api.theatre_director_api import TheatreDirectorApi
from dbpedia.api.thing_api import ThingApi
from dbpedia.api.time_period_api import TimePeriodApi
from dbpedia.api.topical_concept_api import TopicalConceptApi
from dbpedia.api.tournament_api import TournamentApi
from dbpedia.api.tower_api import TowerApi
from dbpedia.api.town_api import TownApi
from dbpedia.api.track_list_api import TrackListApi
from dbpedia.api.trade_union_api import TradeUnionApi
from dbpedia.api.train_api import TrainApi
from dbpedia.api.treadmill_api import TreadmillApi
from dbpedia.api.tunnel_api import TunnelApi
from dbpedia.api.type_api import TypeApi
from dbpedia.api.unit_of_work_api import UnitOfWorkApi
from dbpedia.api.university_api import UniversityApi
from dbpedia.api.unknown_api import UnknownApi
from dbpedia.api.valley_api import ValleyApi
from dbpedia.api.vein_api import VeinApi
from dbpedia.api.venue_api import VenueApi
from dbpedia.api.vicar_api import VicarApi
from dbpedia.api.vice_president_api import VicePresidentApi
from dbpedia.api.vice_prime_minister_api import VicePrimeMinisterApi
from dbpedia.api.video_game_api import VideoGameApi
from dbpedia.api.videogames_league_api import VideogamesLeagueApi
from dbpedia.api.village_api import VillageApi
from dbpedia.api.voice_actor_api import VoiceActorApi
from dbpedia.api.volcano_api import VolcanoApi
from dbpedia.api.volleyball_coach_api import VolleyballCoachApi
from dbpedia.api.volleyball_league_api import VolleyballLeagueApi
from dbpedia.api.volleyball_player_api import VolleyballPlayerApi
from dbpedia.api.water_polo_player_api import WaterPoloPlayerApi
from dbpedia.api.water_ride_api import WaterRideApi
from dbpedia.api.water_tower_api import WaterTowerApi
from dbpedia.api.watermill_api import WatermillApi
from dbpedia.api.waterway_tunnel_api import WaterwayTunnelApi
from dbpedia.api.weapon_api import WeaponApi
from dbpedia.api.website_api import WebsiteApi
from dbpedia.api.wind_motor_api import WindMotorApi
from dbpedia.api.windmill_api import WindmillApi
from dbpedia.api.wine_api import WineApi
from dbpedia.api.wine_region_api import WineRegionApi
from dbpedia.api.winery_api import WineryApi
from dbpedia.api.womens_tennis_association_tournament_api import WomensTennisAssociationTournamentApi
from dbpedia.api.work_api import WorkApi
from dbpedia.api.world_heritage_site_api import WorldHeritageSiteApi
from dbpedia.api.wrestler_api import WrestlerApi
from dbpedia.api.wrestling_event_api import WrestlingEventApi
from dbpedia.api.writer_api import WriterApi
from dbpedia.api.written_work_api import WrittenWorkApi
from dbpedia.api.year_api import YearApi
from dbpedia.api.year_in_spaceflight_api import YearInSpaceflightApi
from dbpedia.api.zoo_api import ZooApi
from dbpedia.api.openswarm_api import OpenswarmApi
