
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-11T22:59:34+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5f7c80aca3de6bb5ba4f575eaa0cfd8fc9dbe53",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
